/**
 * Icon helper: content catalogs use loose icon names (lucide-ish). We resolve them
 * against MaterialCommunityIcons, then Ionicons, with a small alias table and a safe fallback.
 */
import React from 'react';
import { MaterialCommunityIcons, Ionicons } from '@expo/vector-icons';
import type { StyleProp, TextStyle } from 'react-native';
import type { ActionCategory, VenueArchetype, WeatherCondition, TravelMode } from '@engine/core/types';

const MCI = MaterialCommunityIcons as unknown as React.ComponentType<{ name: string; size?: number; color?: string; style?: StyleProp<TextStyle> }>;
const ION = Ionicons as unknown as React.ComponentType<{ name: string; size?: number; color?: string; style?: StyleProp<TextStyle> }>;
const mciMap = (MaterialCommunityIcons as unknown as { glyphMap: Record<string, number> }).glyphMap ?? {};
const ionMap = (Ionicons as unknown as { glyphMap: Record<string, number> }).glyphMap ?? {};

const ALIASES: Record<string, string> = {
  sparkles: 'creation',
  sparkle: 'creation',
  museum: 'bank',
  dart: 'bullseye-arrow',
  karaoke: 'microphone-variant',
  arcade: 'controller-classic',
  utensils: 'silverware-fork-knife',
  'utensils-crossed': 'silverware-fork-knife',
  'glass-water': 'cup-water',
  zap: 'lightning-bolt',
  droplet: 'water',
  droplets: 'water',
  bath: 'bathtub',
  users: 'account-group',
  user: 'account',
  'user-plus': 'account-plus',
  smile: 'emoticon-happy-outline',
  frown: 'emoticon-sad-outline',
  armchair: 'sofa',
  bed: 'bed',
  'bed-double': 'bed-king',
  'shopping-cart': 'cart',
  'shopping-bag': 'shopping',
  'message-circle': 'message-text',
  'message-square': 'message-text',
  'phone-call': 'phone-in-talk',
  'trending-up': 'trending-up',
  'book-open': 'book-open-variant',
  'graduation-cap': 'school',
  'briefcase': 'briefcase',
  'dollar-sign': 'currency-usd',
  'banknote': 'cash',
  'credit-card': 'credit-card',
  'heart': 'heart',
  'heart-handshake': 'handshake',
  'party-popper': 'party-popper',
  'gamepad-2': 'gamepad-variant',
  gamepad: 'gamepad-variant',
  tv: 'television',
  'tv-2': 'television',
  music: 'music',
  music2: 'music',
  'music-2': 'music',
  palette: 'palette',
  'paint-brush': 'brush',
  paintbrush: 'brush',
  dumbbell: 'dumbbell',
  bike: 'bike',
  car: 'car',
  bus: 'bus',
  train: 'train',
  plane: 'airplane',
  footprints: 'walk',
  'foot-print': 'walk',
  'map-pin': 'map-marker',
  home: 'home',
  house: 'home',
  building: 'office-building',
  'building-2': 'office-building',
  store: 'store',
  coffee: 'coffee',
  beer: 'beer',
  wine: 'glass-wine',
  martini: 'glass-cocktail',
  pill: 'pill',
  stethoscope: 'stethoscope',
  syringe: 'needle',
  'paw-print': 'paw',
  dog: 'dog',
  cat: 'cat',
  'baby': 'baby-face',
  'shield': 'shield',
  'shield-alert': 'shield-alert',
  gavel: 'gavel',
  scale: 'scale-balance',
  'scale-balance': 'scale-balance',
  siren: 'alarm-light',
  'alert-triangle': 'alert',
  'alert-circle': 'alert-circle',
  info: 'information-outline',
  clock: 'clock-outline',
  timer: 'timer-outline',
  calendar: 'calendar',
  sun: 'weather-sunny',
  moon: 'weather-night',
  'cloud-rain': 'weather-rainy',
  cloud: 'weather-cloudy',
  snowflake: 'snowflake',
  wind: 'weather-windy',
  flame: 'fire',
  fire: 'fire',
  wrench: 'wrench',
  hammer: 'hammer',
  broom: 'broom',
  'washing-machine': 'washing-machine',
  shirt: 'tshirt-crew',
  scissors: 'content-cut',
  laptop: 'laptop',
  monitor: 'monitor',
  smartphone: 'cellphone',
  phone: 'phone',
  search: 'magnify',
  send: 'send',
  'chef-hat': 'chef-hat',
  'cooking-pot': 'pot-steam',
  pizza: 'pizza',
  apple: 'food-apple',
  sandwich: 'food',
  'ice-cream': 'ice-cream',
  cake: 'cake-variant',
  egg: 'egg',
  sofa: 'sofa',
  lamp: 'lamp',
  'book': 'book',
  library: 'library',
  newspaper: 'newspaper',
  pen: 'pencil',
  pencil: 'pencil',
  camera: 'camera',
  guitar: 'guitar-acoustic',
  piano: 'piano',
  mic: 'microphone',
  'mic-2': 'microphone',
  film: 'movie-open',
  ticket: 'ticket',
  trophy: 'trophy',
  target: 'bullseye-arrow',
  flag: 'flag',
  star: 'star',
  gift: 'gift',
  flower: 'flower',
  'flower-2': 'flower-tulip',
  leaf: 'leaf',
  trees: 'pine-tree',
  tree: 'tree',
  tent: 'tent',
  fish: 'fish',
  church: 'church',
  cross: 'cross',
  brain: 'brain',
  'heart-pulse': 'heart-pulse',
  activity: 'pulse',
  bandage: 'bandage',
  cigarette: 'cigar',
  cannabis: 'cannabis',
  lock: 'lock',
  key: 'key-variant',
  package: 'package-variant',
  truck: 'truck-delivery',
  mail: 'email',
  mailbox: 'mailbox',
  bank: 'bank',
  'piggy-bank': 'piggy-bank',
  receipt: 'receipt',
  wallet: 'wallet',
  'hand-coins': 'hand-coin',
  coins: 'cash-multiple',
  'badge-dollar-sign': 'currency-usd',
  dice: 'dice-5',
  'dice-5': 'dice-5',
  'more-horizontal': 'dots-horizontal',
  ellipsis: 'dots-horizontal',
  x: 'close',
  check: 'check',
  plus: 'plus',
  minus: 'minus',
  'chevron-right': 'chevron-right',
  'chevron-down': 'chevron-down',
  'arrow-left': 'arrow-left',
  settings: 'cog',
  eye: 'eye',
  'eye-off': 'eye-off',
  handshake: 'handshake',
  hand: 'hand-wave',
  sleep: 'sleep',
  bathtub: 'bathtub',
  toilet: 'toilet',
  shower: 'shower-head',
  'shower-head': 'shower-head',
  sink: 'water-pump',
  fridge: 'fridge-outline',
  refrigerator: 'fridge-outline',
  microwave: 'microwave',
  stove: 'stove',
  oven: 'stove',
  toaster: 'toaster',
  blender: 'blender',
  kettle: 'kettle',
  'coffee-maker': 'coffee-maker',
  'espresso': 'coffee-maker',
  dishwasher: 'dishwasher',
  'trash': 'trash-can-outline',
  'trash-2': 'trash-can-outline',
  vacuum: 'robot-vacuum',
  thermometer: 'thermometer',
  fan: 'fan',
  'air-vent': 'air-conditioner',
  heater: 'radiator',
  'smoke-detector': 'smoke-detector',
  cctv: 'cctv',
  'door-closed': 'door-closed',
  'door-open': 'door-open',
  treadmill: 'run',
  weights: 'weight-lifter',
  yoga: 'yoga',
  'bike-fast': 'bike-fast',
  boxing: 'boxing-glove',
  easel: 'palette',
  pottery: 'pot',
  sewing: 'needle',
  workbench: 'hammer-wrench',
  toolbox: 'toolbox',
  garden: 'sprout',
  planter: 'flower-pot',
  mower: 'mower',
  grill: 'grill',
  campfire: 'campfire',
  patio: 'table-chair',
  'hot-tub': 'hot-tub',
  pool: 'pool',
  hammock: 'weather-night',
  'bike-rack': 'bike',
  charger: 'ev-station',
  'dog-bed': 'dog',
  'cat-tree': 'cat',
  'litter-box': 'cat',
  aquarium: 'fish',
  'bird-cage': 'bird',
  hamster: 'rodent',
  'toy-box': 'toy-brick',
  'board-game': 'dice-multiple',
  puzzle: 'puzzle',
  chess: 'chess-knight',
  telescope: 'telescope',
  'bar-cart': 'glass-cocktail',
  'wine-rack': 'bottle-wine',
  humidor: 'cigar',
  safe: 'safe',
  'file-cabinet': 'file-cabinet',
  printer: 'printer',
  'cash-register': 'cash-register',
  'self-checkout': 'barcode-scan',
  'shopping-basket': 'basket',
  shelf: 'bookshelf',
  produce: 'food-apple',
  deli: 'food-steak',
  bakery: 'bread-slice',
  pharmacy: 'pill',
  atm: 'cash-multiple',
  teller: 'bank',
  'cafe-table': 'coffee',
  barista: 'coffee-maker',
  restaurant: 'silverware-fork-knife',
  'host-stand': 'account-tie',
  kitchen: 'chef-hat',
  bar: 'glass-cocktail',
  'bar-stool': 'seat',
  'dance-floor': 'dance-ballroom',
  dj: 'album',
  stage: 'theater',
  jukebox: 'music-box',
  'pool-table': 'billiards',
  'claw-machine': 'robot-industrial',
  bowling: 'bowling',
  'slot-machine': 'slot-machine',
  poker: 'poker-chip',
  roulette: 'poker-chip',
  sauna: 'spa',
  basketball: 'basketball',
  tennis: 'tennis',
  soccer: 'soccer',
  baseball: 'baseball',
  golf: 'golf',
  climbing: 'carabiner',
  'ice-rink': 'skate',
  massage: 'spa',
  salon: 'content-cut',
  barber: 'content-cut',
  nail: 'hand-back-right',
  tattoo: 'draw',
  tanning: 'white-balance-sunny',
  'exam-table': 'hospital-box',
  'hospital-bed': 'bed',
  dental: 'tooth',
  xray: 'radiology-box',
  vet: 'paw',
  kennel: 'dog-side',
  adoption: 'paw',
  'study-table': 'desk',
  computer: 'desktop-classic',
  lecture: 'school',
  classroom: 'school',
  whiteboard: 'presentation',
  lab: 'flask',
  locker: 'locker',
  cafeteria: 'silverware',
  'office-desk': 'desk',
  conference: 'account-group',
  cubicle: 'desk',
  'water-cooler': 'cup-water',
  copier: 'printer',
  warehouse: 'warehouse',
  forklift: 'forklift',
  'assembly-line': 'robot-industrial',
  'cinema-seat': 'seat',
  concession: 'popcorn',
  exhibit: 'image-frame',
  zoo: 'elephant',
  coaster: 'ferris-wheel',
  'ferris-wheel': 'ferris-wheel',
  carousel: 'horse',
  bench: 'seat-outline',
  picnic: 'table-picnic',
  playground: 'slide',
  swing: 'human-child',
  trail: 'hiking',
  pier: 'fish',
  beach: 'beach',
  volleyball: 'volleyball',
  restroom: 'toilet',
  vending: 'bottle-soda',
  'food-truck': 'truck',
  stall: 'storefront',
  'bus-stop': 'bus-stop',
  platform: 'train',
  kiosk: 'ticket-confirmation',
  gate: 'airplane-takeoff',
  security: 'shield-check',
  pump: 'gas-station',
  'car-wash': 'car-wash',
  lift: 'car-lifted-pickup',
  parts: 'car-cog',
  lot: 'car-multiple',
  rental: 'car-key',
  parking: 'parking',
  'hotel-bed': 'bed-king',
  lobby: 'bell',
  pew: 'church',
  altar: 'candle',
  candle: 'candle',
  'community-table': 'account-group',
  'soup-kitchen': 'pot-steam',
  cot: 'bed-single',
  court: 'gavel',
  judge: 'gavel',
  jury: 'account-group',
  cell: 'lock',
  bunk: 'bunk-bed',
  'police-desk': 'police-badge',
  'fire-engine': 'fire-truck',
  post: 'email',
  dmv: 'card-account-details',
  'city-hall': 'city',
  lawyer: 'scale-balance',
  accountant: 'calculator',
  insurance: 'shield-check',
  realtor: 'home-city',
  storage: 'garage',
  'thrift-rack': 'hanger',
  'clothing-rack': 'hanger',
  'fitting-room': 'tshirt-crew',
  electronics: 'television',
  furniture: 'sofa',
  hardware: 'hammer-wrench',
  bookstore: 'bookshelf',
  liquor: 'bottle-wine',
  dispensary: 'cannabis',
  florist: 'flower',
  butcher: 'food-steak',
};

export function resolveIconName(name?: string | null): { family: 'mci' | 'ion'; name: string } {
  if (!name) return { family: 'mci', name: 'circle-small' };
  const raw = name.trim();
  if (mciMap[raw]) return { family: 'mci', name: raw };
  const alias = ALIASES[raw];
  if (alias && mciMap[alias]) return { family: 'mci', name: alias };
  if (ionMap[raw]) return { family: 'ion', name: raw };
  const outline = `${raw}-outline`;
  if (mciMap[outline]) return { family: 'mci', name: outline };
  if (ionMap[outline]) return { family: 'ion', name: outline };
  return { family: 'mci', name: 'circle-small' };
}

export interface IconProps {
  name?: string | null;
  size?: number;
  color?: string;
  style?: StyleProp<TextStyle>;
}

export function Icon({ name, size = 18, color = '#EDF1F7', style }: IconProps): React.ReactElement {
  const r = resolveIconName(name);
  if (r.family === 'ion') return <ION name={r.name} size={size} color={color} style={style} />;
  return <MCI name={r.name} size={size} color={color} style={style} />;
}

export const CATEGORY_ICON: Record<ActionCategory, string> = {
  needs: 'silverware-fork-knife',
  social: 'account-group',
  romance: 'heart',
  work: 'briefcase',
  school: 'school',
  travel: 'map-marker',
  shop: 'cart',
  object: 'cube-outline',
  phone: 'cellphone',
  hobby: 'palette',
  fitness: 'dumbbell',
  chores: 'broom',
  finance: 'bank',
  legal: 'gavel',
  health: 'hospital-box',
  pet: 'paw',
  family: 'home-heart',
  entertainment: 'television',
  civic: 'city',
  freeform: 'creation',
  system: 'cog',
};

export const CATEGORY_LABEL: Record<ActionCategory, string> = {
  needs: 'Needs',
  social: 'Social',
  romance: 'Romance',
  work: 'Work',
  school: 'School',
  travel: 'Travel',
  shop: 'Shopping',
  object: 'Objects',
  phone: 'Phone',
  hobby: 'Hobbies',
  fitness: 'Fitness',
  chores: 'Chores',
  finance: 'Finance',
  legal: 'Legal',
  health: 'Health',
  pet: 'Pets',
  family: 'Family',
  entertainment: 'Entertainment',
  civic: 'Civic',
  freeform: 'Freeform',
  system: 'System',
};

export const ARCHETYPE_ICON: Record<VenueArchetype, string> = {
  home: 'home',
  apartment_building: 'office-building',
  grocery: 'cart',
  convenience: 'store',
  restaurant: 'silverware-fork-knife',
  fast_food: 'hamburger',
  cafe: 'coffee',
  bar: 'glass-cocktail',
  nightclub: 'music',
  gym: 'dumbbell',
  park: 'tree',
  playground: 'slide',
  trail: 'hiking',
  beach: 'beach',
  school: 'school',
  daycare: 'baby-face',
  college: 'school',
  library: 'library',
  hospital: 'hospital-box',
  clinic: 'stethoscope',
  dentist: 'tooth',
  pharmacy: 'pill',
  vet: 'paw',
  pet_store: 'dog',
  police: 'police-badge',
  fire_station: 'fire-truck',
  courthouse: 'gavel',
  jail: 'lock',
  dmv: 'card-account-details',
  city_hall: 'city',
  post_office: 'email',
  bank: 'bank',
  atm: 'cash-multiple',
  office: 'office-building',
  coworking: 'laptop',
  factory: 'factory',
  warehouse: 'warehouse',
  retail: 'shopping',
  clothing: 'hanger',
  electronics: 'television',
  furniture: 'sofa',
  hardware: 'hammer-wrench',
  bookstore: 'bookshelf',
  mall: 'store',
  liquor_store: 'bottle-wine',
  dispensary: 'cannabis',
  cinema: 'movie-open',
  theater: 'theater',
  concert_hall: 'music-clef-treble',
  stadium: 'stadium',
  arena: 'stadium',
  museum: 'bank',
  zoo: 'elephant',
  aquarium: 'fish',
  amusement_park: 'ferris-wheel',
  bowling: 'bowling',
  arcade: 'controller-classic',
  casino: 'slot-machine',
  church: 'church',
  salon: 'content-cut',
  barber: 'content-cut',
  spa: 'spa',
  tattoo: 'draw',
  laundromat: 'washing-machine',
  car_dealer: 'car-multiple',
  car_rental: 'car-key',
  gas_station: 'gas-station',
  ev_charger: 'ev-station',
  mechanic: 'wrench',
  car_wash: 'car-wash',
  parking: 'parking',
  transit_stop: 'bus-stop',
  train_station: 'train',
  bus_station: 'bus',
  airport: 'airplane',
  hotel: 'bed-king',
  community_center: 'account-multiple',
  senior_center: 'human-cane',
  shelter: 'home-heart',
  cemetery: 'grave-stone',
  funeral_home: 'coffin',
  lawyer: 'scale-balance',
  accountant: 'calculator',
  insurance: 'shield-check',
  real_estate: 'home-city',
  storage: 'garage',
  farmers_market: 'basket',
  bakery: 'bread-slice',
  butcher: 'food-steak',
  florist: 'flower',
  thrift_store: 'hanger',
  sports_field: 'soccer',
  golf: 'golf',
  pool: 'pool',
  ice_rink: 'skate',
  climbing_gym: 'carabiner',
  yoga: 'yoga',
  martial_arts: 'karate',
  dance_studio: 'dance-ballroom',
  music_school: 'music-clef-treble',
  art_studio: 'brush',
  unknown: 'map-marker',
};

export type ArchetypeGroup = 'Home' | 'Food & Drink' | 'Shopping' | 'Health' | 'Work & Money' | 'Civic' | 'Learning' | 'Fun' | 'Outdoors' | 'Fitness' | 'Services' | 'Transport' | 'Other';

export const ARCHETYPE_GROUP: Record<VenueArchetype, ArchetypeGroup> = {
  home: 'Home',
  apartment_building: 'Home',
  hotel: 'Home',
  shelter: 'Home',
  grocery: 'Shopping',
  convenience: 'Shopping',
  retail: 'Shopping',
  clothing: 'Shopping',
  electronics: 'Shopping',
  furniture: 'Shopping',
  hardware: 'Shopping',
  bookstore: 'Shopping',
  mall: 'Shopping',
  liquor_store: 'Shopping',
  dispensary: 'Shopping',
  thrift_store: 'Shopping',
  farmers_market: 'Shopping',
  pet_store: 'Shopping',
  florist: 'Shopping',
  restaurant: 'Food & Drink',
  fast_food: 'Food & Drink',
  cafe: 'Food & Drink',
  bar: 'Food & Drink',
  nightclub: 'Food & Drink',
  bakery: 'Food & Drink',
  butcher: 'Food & Drink',
  gym: 'Fitness',
  yoga: 'Fitness',
  martial_arts: 'Fitness',
  climbing_gym: 'Fitness',
  pool: 'Fitness',
  ice_rink: 'Fitness',
  sports_field: 'Fitness',
  golf: 'Fitness',
  dance_studio: 'Fitness',
  park: 'Outdoors',
  playground: 'Outdoors',
  trail: 'Outdoors',
  beach: 'Outdoors',
  cemetery: 'Outdoors',
  school: 'Learning',
  daycare: 'Learning',
  college: 'Learning',
  library: 'Learning',
  music_school: 'Learning',
  art_studio: 'Learning',
  hospital: 'Health',
  clinic: 'Health',
  dentist: 'Health',
  pharmacy: 'Health',
  vet: 'Health',
  spa: 'Health',
  police: 'Civic',
  fire_station: 'Civic',
  courthouse: 'Civic',
  jail: 'Civic',
  dmv: 'Civic',
  city_hall: 'Civic',
  post_office: 'Civic',
  church: 'Civic',
  community_center: 'Civic',
  senior_center: 'Civic',
  bank: 'Work & Money',
  atm: 'Work & Money',
  office: 'Work & Money',
  coworking: 'Work & Money',
  factory: 'Work & Money',
  warehouse: 'Work & Money',
  lawyer: 'Work & Money',
  accountant: 'Work & Money',
  insurance: 'Work & Money',
  real_estate: 'Work & Money',
  cinema: 'Fun',
  theater: 'Fun',
  concert_hall: 'Fun',
  stadium: 'Fun',
  arena: 'Fun',
  museum: 'Fun',
  zoo: 'Fun',
  aquarium: 'Fun',
  amusement_park: 'Fun',
  bowling: 'Fun',
  arcade: 'Fun',
  casino: 'Fun',
  salon: 'Services',
  barber: 'Services',
  tattoo: 'Services',
  laundromat: 'Services',
  storage: 'Services',
  funeral_home: 'Services',
  mechanic: 'Services',
  car_wash: 'Services',
  car_dealer: 'Transport',
  car_rental: 'Transport',
  gas_station: 'Transport',
  ev_charger: 'Transport',
  parking: 'Transport',
  transit_stop: 'Transport',
  train_station: 'Transport',
  bus_station: 'Transport',
  airport: 'Transport',
  unknown: 'Other',
};

export const GROUP_ORDER: ArchetypeGroup[] = ['Home', 'Food & Drink', 'Shopping', 'Fun', 'Outdoors', 'Fitness', 'Health', 'Work & Money', 'Learning', 'Civic', 'Services', 'Transport', 'Other'];

export const WEATHER_ICON: Record<WeatherCondition, string> = {
  clear: 'weather-sunny',
  partly_cloudy: 'weather-partly-cloudy',
  cloudy: 'weather-cloudy',
  rain: 'weather-rainy',
  heavy_rain: 'weather-pouring',
  thunderstorm: 'weather-lightning',
  snow: 'weather-snowy',
  sleet: 'weather-snowy-rainy',
  fog: 'weather-fog',
  windy: 'weather-windy',
  heat_wave: 'white-balance-sunny',
  hurricane: 'weather-hurricane',
  tornado_watch: 'weather-tornado',
  smoke: 'smoke',
};

export const TRAVEL_ICON: Record<TravelMode, string> = {
  walk: 'walk',
  bike: 'bike',
  drive: 'car',
  transit: 'bus',
  rideshare: 'car-clock',
  taxi: 'taxi',
  carpool: 'car-multiple',
  scooter: 'scooter',
  fly: 'airplane',
};

export const TRAVEL_LABEL: Record<TravelMode, string> = {
  walk: 'Walk',
  bike: 'Bike',
  drive: 'Drive',
  transit: 'Transit',
  rideshare: 'Rideshare',
  taxi: 'Taxi',
  carpool: 'Carpool',
  scooter: 'Scooter',
  fly: 'Fly',
};
