/**
 * Crime catalog — every `CrimeId` in docs/IDS.md.
 *
 * `detection` is the baseline chance of being caught when nobody is watching; the law
 * system multiplies it by witnesses (×3), venue safety, police heat and cameras.
 * Fines and jail ranges follow typical present-day US state sentencing for a first
 * offense; repeat offenders and felonies land at the top of the range.
 */
import type { CrimeDef } from './types';

const crime = (o: CrimeDef): CrimeDef => o;

export const CRIMES: Record<string, CrimeDef> = {
  shoplifting: crime({
    id: 'shoplifting',
    label: 'Shoplifting',
    severity: 'misdemeanor',
    detection: 0.35,
    fineRange: [100, 1000],
    jailDaysRange: [0, 30],
    probationDays: 180,
    description: 'Concealing merchandise and walking out without paying. Under $100 is often a citation; over $500 escalates.',
    gainRange: [8, 120],
    skillId: 'charisma',
    tags: ['theft', 'property', 'retail'],
  }),
  petty_theft: crime({
    id: 'petty_theft',
    label: 'Petty theft',
    severity: 'misdemeanor',
    detection: 0.3,
    fineRange: [150, 1000],
    jailDaysRange: [0, 90],
    probationDays: 365,
    description: 'Taking property worth less than about $1,000 — a wallet, a bike, a package off a porch.',
    gainRange: [10, 400],
    skillId: 'athletics',
    tags: ['theft', 'property'],
  }),
  grand_theft: crime({
    id: 'grand_theft',
    label: 'Grand theft',
    severity: 'felony',
    detection: 0.45,
    fineRange: [1000, 10000],
    jailDaysRange: [90, 1095],
    probationDays: 1095,
    description: 'Theft of property worth over $1,000 — a car, jewelry, a large cash haul.',
    gainRange: [1000, 8000],
    skillId: 'logic',
    tags: ['theft', 'property', 'felony'],
  }),
  burglary: crime({
    id: 'burglary',
    label: 'Burglary',
    severity: 'felony',
    detection: 0.4,
    fineRange: [1000, 10000],
    jailDaysRange: [180, 2190],
    probationDays: 1095,
    description: 'Breaking into a home or business to commit a crime inside.',
    gainRange: [200, 5000],
    skillId: 'handiness',
    tags: ['theft', 'property', 'felony', 'violent_adjacent'],
  }),
  robbery: crime({
    id: 'robbery',
    label: 'Robbery',
    severity: 'felony',
    detection: 0.55,
    fineRange: [2000, 20000],
    jailDaysRange: [365, 3650],
    probationDays: 1825,
    description: 'Taking property from a person by force or threat.',
    gainRange: [50, 2500],
    skillId: 'athletics',
    tags: ['theft', 'violent', 'felony'],
  }),
  vandalism: crime({
    id: 'vandalism',
    label: 'Vandalism',
    severity: 'misdemeanor',
    detection: 0.25,
    fineRange: [200, 2000],
    jailDaysRange: [0, 60],
    probationDays: 180,
    description: 'Defacing or damaging property — tagging, smashing, keying a car.',
    skillId: 'painting',
    tags: ['property'],
  }),
  assault: crime({
    id: 'assault',
    label: 'Assault',
    severity: 'misdemeanor',
    detection: 0.6,
    fineRange: [500, 4000],
    jailDaysRange: [0, 365],
    probationDays: 365,
    description: 'Threatening or attempting to physically harm someone. Aggravated assault is charged as a felony.',
    skillId: 'athletics',
    tags: ['violent'],
  }),
  battery: crime({
    id: 'battery',
    label: 'Battery',
    severity: 'misdemeanor',
    detection: 0.65,
    fineRange: [500, 4000],
    jailDaysRange: [0, 365],
    probationDays: 365,
    description: 'Actually striking or unlawfully touching someone.',
    skillId: 'athletics',
    tags: ['violent'],
  }),
  dui: crime({
    id: 'dui',
    label: 'Driving under the influence',
    severity: 'misdemeanor',
    detection: 0.2,
    fineRange: [1000, 4000],
    jailDaysRange: [1, 180],
    probationDays: 365,
    licensePoints: 6,
    description: 'Driving with a BAC of 0.08 or higher. First offense usually means license suspension, fines, classes and an ignition interlock.',
    skillId: 'driving',
    tags: ['traffic', 'alcohol', 'license'],
  }),
  speeding: crime({
    id: 'speeding',
    label: 'Speeding',
    severity: 'infraction',
    detection: 0.12,
    fineRange: [120, 400],
    jailDaysRange: [0, 0],
    probationDays: 0,
    licensePoints: 2,
    description: 'Exceeding the posted limit. The ticket scales with how far over you were.',
    skillId: 'driving',
    tags: ['traffic'],
  }),
  reckless_driving: crime({
    id: 'reckless_driving',
    label: 'Reckless driving',
    severity: 'misdemeanor',
    detection: 0.3,
    fineRange: [300, 2500],
    jailDaysRange: [0, 90],
    probationDays: 180,
    licensePoints: 4,
    description: 'Driving with willful disregard for safety — street racing, 25+ over, weaving through traffic.',
    skillId: 'driving',
    tags: ['traffic', 'license'],
  }),
  hit_and_run: crime({
    id: 'hit_and_run',
    label: 'Hit and run',
    severity: 'felony',
    detection: 0.5,
    fineRange: [1000, 10000],
    jailDaysRange: [30, 1460],
    probationDays: 1095,
    licensePoints: 6,
    description: 'Leaving the scene of an accident without stopping to exchange information or help.',
    skillId: 'driving',
    tags: ['traffic', 'felony', 'license'],
  }),
  driving_without_license: crime({
    id: 'driving_without_license',
    label: 'Driving without a license',
    severity: 'misdemeanor',
    detection: 0.15,
    fineRange: [200, 1000],
    jailDaysRange: [0, 30],
    probationDays: 0,
    licensePoints: 3,
    description: 'Driving with no license, or on a suspended or revoked one.',
    tags: ['traffic', 'license'],
  }),
  expired_registration: crime({
    id: 'expired_registration',
    label: 'Expired registration',
    severity: 'infraction',
    detection: 0.1,
    fineRange: [75, 250],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Driving a vehicle whose registration tags have lapsed.',
    tags: ['traffic', 'paperwork'],
  }),
  parking_violation: crime({
    id: 'parking_violation',
    label: 'Parking violation',
    severity: 'infraction',
    detection: 0.35,
    fineRange: [35, 150],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Expired meter, fire lane, blocked hydrant or no-parking zone.',
    tags: ['traffic', 'parking'],
  }),
  jaywalking: crime({
    id: 'jaywalking',
    label: 'Jaywalking',
    severity: 'infraction',
    detection: 0.03,
    fineRange: [25, 200],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Crossing mid-block or against the signal. Rarely enforced, occasionally ticketed.',
    tags: ['pedestrian', 'minor'],
  }),
  littering: crime({
    id: 'littering',
    label: 'Littering',
    severity: 'infraction',
    detection: 0.05,
    fineRange: [50, 500],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Tossing trash on the street or in a park.',
    tags: ['minor', 'environment'],
  }),
  noise_violation: crime({
    id: 'noise_violation',
    label: 'Noise violation',
    severity: 'infraction',
    detection: 0.2,
    fineRange: [100, 500],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Loud music or a party after quiet hours. A neighbor complaint brings the police to the door.',
    tags: ['minor', 'neighborhood'],
  }),
  public_intoxication: crime({
    id: 'public_intoxication',
    label: 'Public intoxication',
    severity: 'misdemeanor',
    detection: 0.25,
    fineRange: [100, 500],
    jailDaysRange: [0, 5],
    probationDays: 0,
    description: 'Being visibly drunk or high in public to the point of endangering yourself or others.',
    tags: ['alcohol', 'minor'],
  }),
  disorderly_conduct: crime({
    id: 'disorderly_conduct',
    label: 'Disorderly conduct',
    severity: 'misdemeanor',
    detection: 0.4,
    fineRange: [100, 1000],
    jailDaysRange: [0, 30],
    probationDays: 90,
    description: 'Fighting, threatening, or creating a public disturbance.',
    tags: ['minor', 'public'],
  }),
  trespassing: crime({
    id: 'trespassing',
    label: 'Trespassing',
    severity: 'misdemeanor',
    detection: 0.3,
    fineRange: [100, 1000],
    jailDaysRange: [0, 30],
    probationDays: 90,
    description: 'Entering or staying on property without permission — a closed business, a construction site, private land.',
    skillId: 'athletics',
    tags: ['property', 'minor'],
  }),
  drug_possession: crime({
    id: 'drug_possession',
    label: 'Drug possession',
    severity: 'misdemeanor',
    detection: 0.15,
    fineRange: [250, 5000],
    jailDaysRange: [0, 365],
    probationDays: 365,
    description: 'Possessing a controlled substance for personal use. Cannabis is legal in some states; harder drugs are not.',
    tags: ['drugs'],
  }),
  drug_dealing: crime({
    id: 'drug_dealing',
    label: 'Drug distribution',
    severity: 'felony',
    detection: 0.2,
    fineRange: [2000, 50000],
    jailDaysRange: [180, 3650],
    probationDays: 1825,
    description: 'Selling or possessing with intent to distribute. Quantity and substance drive the sentence.',
    gainRange: [50, 600],
    skillId: 'negotiation',
    tags: ['drugs', 'felony'],
  }),
  fraud: crime({
    id: 'fraud',
    label: 'Fraud',
    severity: 'felony',
    detection: 0.35,
    fineRange: [2000, 50000],
    jailDaysRange: [90, 1825],
    probationDays: 1095,
    description: 'Lying for financial gain — bad checks, insurance scams, fake invoices.',
    gainRange: [500, 10000],
    skillId: 'logic',
    tags: ['financial', 'felony', 'white_collar'],
  }),
  identity_theft: crime({
    id: 'identity_theft',
    label: 'Identity theft',
    severity: 'felony',
    detection: 0.4,
    fineRange: [5000, 50000],
    jailDaysRange: [180, 2555],
    probationDays: 1095,
    description: "Using someone else's personal information to open accounts or make purchases.",
    gainRange: [500, 15000],
    skillId: 'programming',
    tags: ['financial', 'felony', 'white_collar'],
  }),
  tax_evasion: crime({
    id: 'tax_evasion',
    label: 'Tax evasion',
    severity: 'felony',
    detection: 0.08,
    fineRange: [5000, 100000],
    jailDaysRange: [0, 1825],
    probationDays: 1095,
    description: 'Willfully failing to file or pay what you owe. The IRS is slow but relentless.',
    gainRange: [1000, 30000],
    skillId: 'finance',
    tags: ['financial', 'felony', 'white_collar'],
  }),
  fare_evasion: crime({
    id: 'fare_evasion',
    label: 'Fare evasion',
    severity: 'infraction',
    detection: 0.05,
    fineRange: [50, 250],
    jailDaysRange: [0, 0],
    probationDays: 0,
    description: 'Riding the bus or train without paying.',
    gainRange: [2.5, 2.5],
    tags: ['transit', 'minor'],
  }),
  underage_drinking: crime({
    id: 'underage_drinking',
    label: 'Underage drinking',
    severity: 'misdemeanor',
    detection: 0.2,
    fineRange: [100, 500],
    jailDaysRange: [0, 0],
    probationDays: 90,
    description: 'Possessing or drinking alcohol under 21. Usually a citation, a class, and a very awkward call home.',
    tags: ['alcohol', 'minor', 'youth'],
  }),
  illegal_gambling: crime({
    id: 'illegal_gambling',
    label: 'Illegal gambling',
    severity: 'misdemeanor',
    detection: 0.1,
    fineRange: [250, 2000],
    jailDaysRange: [0, 90],
    probationDays: 180,
    description: 'Running or joining an unlicensed poker game, book, or numbers racket.',
    gainRange: [20, 2000],
    skillId: 'logic',
    tags: ['vice'],
  }),
  prostitution: crime({
    id: 'prostitution',
    label: 'Prostitution',
    severity: 'misdemeanor',
    detection: 0.25,
    fineRange: [500, 2000],
    jailDaysRange: [0, 180],
    probationDays: 365,
    description: 'Exchanging sex for money. Illegal everywhere in the US except parts of Nevada.',
    gainRange: [100, 500],
    tags: ['vice'],
  }),
  arson: crime({
    id: 'arson',
    label: 'Arson',
    severity: 'felony',
    detection: 0.5,
    fineRange: [5000, 50000],
    jailDaysRange: [730, 5475],
    probationDays: 1825,
    description: 'Deliberately setting fire to property.',
    tags: ['property', 'violent', 'felony'],
  }),
  domestic_disturbance: crime({
    id: 'domestic_disturbance',
    label: 'Domestic disturbance',
    severity: 'misdemeanor',
    detection: 0.5,
    fineRange: [200, 2000],
    jailDaysRange: [0, 365],
    probationDays: 365,
    description: 'A fight at home loud or violent enough that someone called the police.',
    tags: ['violent', 'family'],
  }),
  animal_neglect: crime({
    id: 'animal_neglect',
    label: 'Animal neglect',
    severity: 'misdemeanor',
    detection: 0.15,
    fineRange: [250, 5000],
    jailDaysRange: [0, 180],
    probationDays: 365,
    description: 'Failing to provide food, water, shelter or vet care to an animal in your custody.',
    tags: ['animal', 'neglect'],
  }),
  child_neglect: crime({
    id: 'child_neglect',
    label: 'Child neglect',
    severity: 'felony',
    detection: 0.3,
    fineRange: [1000, 10000],
    jailDaysRange: [0, 1825],
    probationDays: 1095,
    description: 'Leaving a child without adequate supervision, food or care. Triggers a CPS investigation.',
    tags: ['family', 'neglect', 'felony'],
  }),
  resisting_arrest: crime({
    id: 'resisting_arrest',
    label: 'Resisting arrest',
    severity: 'misdemeanor',
    detection: 1,
    fineRange: [500, 2500],
    jailDaysRange: [0, 365],
    probationDays: 365,
    description: 'Running from, fighting, or refusing to comply with officers making a lawful arrest.',
    skillId: 'athletics',
    tags: ['police'],
  }),
  contempt_of_court: crime({
    id: 'contempt_of_court',
    label: 'Contempt of court',
    severity: 'misdemeanor',
    detection: 1,
    fineRange: [100, 1000],
    jailDaysRange: [0, 30],
    probationDays: 0,
    description: 'Ignoring a court order, skipping a hearing, or ditching jury duty.',
    tags: ['court'],
  }),
};

export const CRIME_IDS = Object.keys(CRIMES);
