/**
 * Recurring local events (owned by the calendar builder). The calendar system schedules each one
 * once per `month` at a venue matching one of `venues` (first archetype that exists in the world),
 * for `durationDays` days, and exposes `activities` as `festival:<id>:<index>` actions while the
 * player is at that venue during the event window.
 *
 * Prices are national averages at costOfLiving 1.0; the scheduler scales by region.
 */
import type { FestivalDef } from './types';

const F = (def: FestivalDef): FestivalDef => def;

export const FESTIVALS: Record<string, FestivalDef> = {
  lunar_new_year_parade: F({
    id: 'lunar_new_year_parade',
    name: 'Lunar New Year Parade',
    month: 2,
    venues: ['park', 'community_center', 'mall'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Watch the lion dance', cost: 0, fun: 22, social: 15, durationMinutes: 60 },
      { label: 'Eat from the food stalls', cost: 18, fun: 15, social: 10, durationMinutes: 45 },
      { label: 'Buy a red envelope set and decorations', cost: 12, fun: 5, social: 3, durationMinutes: 20 },
    ],
    description: 'Lion dancers, drums, firecrackers, and a mile of street food stalls.',
    crowd: 0.8,
    tags: ['cultural', 'parade', 'food'],
  }),
  ice_rink_season: F({
    id: 'ice_rink_season',
    name: 'Downtown Ice Rink',
    month: 1,
    venues: ['ice_rink', 'park', 'mall'],
    durationDays: 28,
    ticketPrice: 16,
    activities: [
      { label: 'Skate a session', cost: 16, fun: 25, social: 12, durationMinutes: 75, skillId: 'athletics' },
      { label: 'Hot cocoa rinkside', cost: 6, fun: 8, social: 8, durationMinutes: 20 },
    ],
    description: 'The pop-up outdoor rink with rental skates, string lights, and a cocoa stand.',
    crowd: 0.5,
    tags: ['winter', 'family', 'sport'],
  }),
  film_festival: F({
    id: 'film_festival',
    name: 'Independent Film Festival',
    month: 3,
    venues: ['cinema', 'theater', 'college'],
    durationDays: 5,
    ticketPrice: 18,
    activities: [
      { label: 'Screening + director Q&A', cost: 18, fun: 24, social: 10, durationMinutes: 130 },
      { label: 'Shorts block', cost: 14, fun: 18, social: 8, durationMinutes: 95 },
      { label: 'Opening-night party', cost: 30, fun: 22, social: 25, durationMinutes: 150 },
    ],
    description: 'Five days of indie premieres, documentaries, badge holders, and long lines for the buzzy title.',
    crowd: 0.6,
    tags: ['arts', 'film'],
  }),
  marathon: F({
    id: 'marathon',
    name: 'City Marathon & 5K',
    month: 4,
    venues: ['park', 'stadium', 'trail'],
    durationDays: 1,
    ticketPrice: 45,
    activities: [
      { label: 'Run the 5K', cost: 45, fun: 22, social: 12, durationMinutes: 45, skillId: 'athletics' },
      { label: 'Run the half marathon', cost: 95, fun: 28, social: 12, durationMinutes: 150, skillId: 'athletics' },
      { label: 'Cheer from the sidelines', cost: 0, fun: 12, social: 15, durationMinutes: 90 },
    ],
    description: 'Roads close at 5am, runners in costumes, cowbells on every corner, free bananas at the finish.',
    crowd: 0.8,
    tags: ['sport', 'fitness'],
  }),
  farmers_market_season: F({
    id: 'farmers_market_season',
    name: 'Farmers Market Opening Weekend',
    month: 4,
    venues: ['farmers_market', 'park', 'community_center'],
    durationDays: 2,
    ticketPrice: 0,
    activities: [
      { label: 'Browse the stalls and buy produce', cost: 28, fun: 12, social: 10, durationMinutes: 60 },
      { label: 'Grab a breakfast taco and coffee', cost: 11, fun: 10, social: 8, durationMinutes: 30 },
      { label: 'Listen to the busker', cost: 2, fun: 8, social: 5, durationMinutes: 20 },
    ],
    description: 'The Saturday market is back: heirloom tomatoes, kombucha, a guy with a banjo, and dogs everywhere.',
    crowd: 0.6,
    tags: ['food', 'outdoors', 'spring'],
  }),
  art_walk: F({
    id: 'art_walk',
    name: 'First Friday Art Walk',
    month: 5,
    venues: ['art_studio', 'museum', 'retail', 'cafe'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Gallery hop with free wine', cost: 0, fun: 18, social: 18, durationMinutes: 120, skillId: 'painting' },
      { label: 'Buy a print from a local artist', cost: 45, fun: 10, social: 8, durationMinutes: 20 },
    ],
    description: 'Galleries, studios and shops stay open late with wine, live painting, and DJs on the sidewalk.',
    crowd: 0.5,
    tags: ['arts', 'nightlife'],
  }),
  cinco_de_mayo_street_party: F({
    id: 'cinco_de_mayo_street_party',
    name: 'Cinco de Mayo Street Festival',
    month: 5,
    venues: ['park', 'restaurant', 'community_center'],
    durationDays: 1,
    ticketPrice: 5,
    activities: [
      { label: 'Dance to the mariachi and banda', cost: 0, fun: 25, social: 22, durationMinutes: 90, skillId: 'dancing' },
      { label: 'Tacos, elote and a margarita', cost: 22, fun: 16, social: 10, durationMinutes: 45 },
      { label: 'Lucha libre exhibition', cost: 10, fun: 20, social: 10, durationMinutes: 60 },
    ],
    description: 'Blocks of food stands, folklórico dancers, a lucha ring, and a lot of tequila.',
    crowd: 0.8,
    tags: ['cultural', 'food', 'party'],
  }),
  renaissance_faire: F({
    id: 'renaissance_faire',
    name: 'Renaissance Faire',
    month: 5,
    venues: ['park', 'trail', 'amusement_park'],
    durationDays: 9,
    ticketPrice: 32,
    activities: [
      { label: 'Joust and turkey leg', cost: 32, fun: 28, social: 15, durationMinutes: 240 },
      { label: 'Rent a costume and go all in', cost: 55, fun: 32, social: 22, durationMinutes: 300 },
      { label: 'Axe throwing', cost: 12, fun: 18, social: 10, durationMinutes: 30, skillId: 'athletics' },
    ],
    description: 'Huzzah! Jousting, mead, corsets, and a surprising number of people who came in character.',
    crowd: 0.7,
    tags: ['outdoors', 'costume', 'weekend'],
  }),
  juneteenth_celebration: F({
    id: 'juneteenth_celebration',
    name: 'Juneteenth Freedom Festival',
    month: 6,
    venues: ['park', 'community_center', 'church'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Parade and live music', cost: 0, fun: 22, social: 22, durationMinutes: 150 },
      { label: 'Black-owned business market', cost: 35, fun: 12, social: 12, durationMinutes: 60 },
      { label: 'Red soda and barbecue', cost: 16, fun: 14, social: 12, durationMinutes: 45 },
    ],
    description: 'A parade, gospel and R&B stages, a vendor market, and family reunions spilling across the park.',
    crowd: 0.75,
    tags: ['cultural', 'summer', 'music'],
  }),
  pride_parade: F({
    id: 'pride_parade',
    name: 'Pride Parade & Festival',
    month: 6,
    venues: ['park', 'bar', 'nightclub', 'community_center'],
    durationDays: 2,
    ticketPrice: 0,
    activities: [
      { label: 'Watch the parade', cost: 0, fun: 26, social: 25, durationMinutes: 180 },
      { label: 'Festival grounds: drag stage and vendors', cost: 15, fun: 25, social: 25, durationMinutes: 180 },
      { label: 'Pride after-party', cost: 40, fun: 30, social: 30, durationMinutes: 240, skillId: 'dancing' },
    ],
    description: 'Floats, glitter, corporate flags, drag queens on trucks, and the best people-watching of the year.',
    crowd: 0.9,
    tags: ['cultural', 'party', 'summer'],
  }),
  summer_concert_series: F({
    id: 'summer_concert_series',
    name: 'Summer Concerts in the Park',
    month: 7,
    venues: ['park', 'concert_hall', 'community_center'],
    durationDays: 30,
    ticketPrice: 0,
    activities: [
      { label: 'Picnic blanket and a free show', cost: 12, fun: 22, social: 18, durationMinutes: 150, skillId: 'music' },
      { label: 'Dance in front of the stage', cost: 0, fun: 24, social: 20, durationMinutes: 90, skillId: 'dancing' },
    ],
    description: 'Free Thursday-night shows on the lawn: cover bands, a symphony pops night, food trucks lined up by the fountain.',
    crowd: 0.55,
    tags: ['music', 'outdoors', 'free', 'summer'],
  }),
  fourth_of_july_fireworks: F({
    id: 'fourth_of_july_fireworks',
    name: 'Fourth of July Fireworks',
    month: 7,
    venues: ['park', 'beach', 'stadium'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Stake out a spot for the fireworks', cost: 0, fun: 30, social: 22, durationMinutes: 180 },
      { label: 'Funnel cake and lemonade', cost: 14, fun: 12, social: 6, durationMinutes: 30 },
    ],
    description: 'The city show over the water: 20 minutes of fireworks, an hour of traffic afterward.',
    crowd: 0.95,
    tags: ['holiday', 'summer', 'free'],
  }),
  food_truck_festival: F({
    id: 'food_truck_festival',
    name: 'Food Truck Festival',
    month: 8,
    venues: ['park', 'parking', 'community_center'],
    durationDays: 2,
    ticketPrice: 8,
    activities: [
      { label: 'Eat your way down the row', cost: 32, fun: 22, social: 12, durationMinutes: 90 },
      { label: 'Craft beer garden', cost: 18, fun: 16, social: 18, durationMinutes: 60 },
      { label: 'Hot wing eating contest', cost: 0, fun: 20, social: 15, durationMinutes: 30 },
    ],
    description: 'Forty trucks, one beer garden, live band, and a wait for the birria tacos that everyone says is worth it.',
    crowd: 0.7,
    tags: ['food', 'summer'],
  }),
  air_show: F({
    id: 'air_show',
    name: 'Air & Water Show',
    month: 8,
    venues: ['airport', 'beach', 'park'],
    durationDays: 2,
    ticketPrice: 0,
    activities: [
      { label: 'Watch the jet team', cost: 0, fun: 26, social: 12, durationMinutes: 150 },
      { label: 'Tour the static displays', cost: 0, fun: 14, social: 8, durationMinutes: 60 },
    ],
    description: 'Jets ripping over the waterfront, a vintage bomber, and a lot of sunburn.',
    crowd: 0.85,
    tags: ['outdoors', 'summer', 'free'],
  }),
  back_to_school_fair: F({
    id: 'back_to_school_fair',
    name: 'Back-to-School Fair',
    month: 8,
    venues: ['school', 'community_center', 'library', 'church'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Free backpack and supplies', cost: 0, fun: 8, social: 10, durationMinutes: 45 },
      { label: 'Free haircuts and immunizations line', cost: 0, fun: 3, social: 8, durationMinutes: 60 },
    ],
    description: 'Community groups hand out backpacks, do free haircuts, and sign kids up for after-school programs.',
    crowd: 0.5,
    tags: ['family', 'community', 'free'],
  }),
  state_fair: F({
    id: 'state_fair',
    name: 'State Fair',
    month: 9,
    venues: ['amusement_park', 'stadium', 'park'],
    durationDays: 12,
    ticketPrice: 20,
    activities: [
      { label: 'Ride the Ferris wheel and the Zipper', cost: 25, fun: 30, social: 15, durationMinutes: 90 },
      { label: 'Deep-fried everything', cost: 22, fun: 18, social: 8, durationMinutes: 45 },
      { label: 'Livestock barns and the butter sculpture', cost: 0, fun: 14, social: 8, durationMinutes: 60 },
      { label: 'Grandstand concert', cost: 45, fun: 28, social: 18, durationMinutes: 150, skillId: 'music' },
      { label: 'Win a stuffed animal at the midway', cost: 15, fun: 15, social: 10, durationMinutes: 30 },
    ],
    description: 'Twelve days of rides, corn dogs, fried Oreos, 4-H cattle, and a washed-up rock band on the grandstand.',
    crowd: 0.9,
    tags: ['fair', 'family', 'food', 'rides'],
  }),
  county_fair: F({
    id: 'county_fair',
    name: 'County Fair & Rodeo',
    month: 7,
    venues: ['sports_field', 'park', 'amusement_park'],
    durationDays: 5,
    ticketPrice: 12,
    activities: [
      { label: 'Rodeo night', cost: 20, fun: 26, social: 15, durationMinutes: 150 },
      { label: 'Carnival rides', cost: 20, fun: 24, social: 12, durationMinutes: 90 },
      { label: 'Demolition derby', cost: 15, fun: 25, social: 12, durationMinutes: 120 },
      { label: 'Pie contest and 4-H exhibits', cost: 0, fun: 12, social: 10, durationMinutes: 45 },
    ],
    description: 'Smaller than the state fair, bigger on rodeo, tractor pulls and demolition derby.',
    crowd: 0.7,
    tags: ['fair', 'rodeo', 'family'],
  }),
  rodeo: F({
    id: 'rodeo',
    name: 'Stock Show & Rodeo',
    month: 3,
    venues: ['stadium', 'arena', 'sports_field'],
    durationDays: 10,
    ticketPrice: 35,
    activities: [
      { label: 'Bull riding and barrel racing', cost: 35, fun: 28, social: 15, durationMinutes: 150 },
      { label: 'Carnival and BBQ cook-off', cost: 25, fun: 22, social: 15, durationMinutes: 120 },
      { label: 'Post-rodeo concert', cost: 40, fun: 26, social: 20, durationMinutes: 120, skillId: 'music' },
    ],
    description: 'Boots and hats required. Bull riding, mutton bustin\', a barbecue cook-off, and a country headliner every night.',
    crowd: 0.85,
    tags: ['rodeo', 'music', 'food'],
  }),
  oktoberfest: F({
    id: 'oktoberfest',
    name: 'Oktoberfest',
    month: 10,
    venues: ['bar', 'park', 'community_center'],
    durationDays: 3,
    ticketPrice: 10,
    activities: [
      { label: 'Liter steins and a brass band', cost: 28, fun: 25, social: 25, durationMinutes: 150 },
      { label: 'Bratwurst and pretzels', cost: 16, fun: 12, social: 8, durationMinutes: 40 },
      { label: 'Stein-holding contest', cost: 0, fun: 20, social: 18, durationMinutes: 30, skillId: 'fitness' },
    ],
    description: 'Lederhosen, polka, liter steins, and a stein-hoisting contest that someone always loses badly.',
    crowd: 0.7,
    tags: ['drinking', 'food', 'fall'],
  }),
  pumpkin_patch: F({
    id: 'pumpkin_patch',
    name: 'Pumpkin Patch & Corn Maze',
    month: 10,
    venues: ['park', 'trail', 'farmers_market'],
    durationDays: 25,
    ticketPrice: 15,
    activities: [
      { label: 'Get lost in the corn maze', cost: 15, fun: 22, social: 18, durationMinutes: 75 },
      { label: 'Pick a pumpkin and ride the hayride', cost: 22, fun: 18, social: 15, durationMinutes: 90 },
      { label: 'Haunted trail after dark', cost: 25, fun: 26, social: 15, durationMinutes: 60 },
      { label: 'Apple cider donuts', cost: 8, fun: 10, social: 5, durationMinutes: 20 },
    ],
    description: 'Hayrides, cider donuts, a corn maze, goats to feed, and a haunted trail on weekend nights.',
    crowd: 0.6,
    tags: ['fall', 'family', 'outdoors'],
  }),
  beer_festival: F({
    id: 'beer_festival',
    name: 'Craft Beer Festival',
    month: 9,
    venues: ['park', 'bar', 'stadium'],
    durationDays: 1,
    ticketPrice: 55,
    activities: [
      { label: 'Unlimited tastings with the souvenir glass', cost: 55, fun: 26, social: 25, durationMinutes: 210, skillId: 'mixology' },
      { label: 'Designated driver ticket', cost: 15, fun: 12, social: 20, durationMinutes: 210 },
    ],
    description: 'Eighty breweries, tiny pours, a pretzel necklace, and a very slow walk to the rideshare pickup zone.',
    crowd: 0.75,
    tags: ['drinking', 'fall'],
  }),
  comic_con: F({
    id: 'comic_con',
    name: 'Comic Con',
    month: 9,
    venues: ['community_center', 'hotel', 'arena', 'mall'],
    durationDays: 3,
    ticketPrice: 65,
    activities: [
      { label: 'Cosplay and the exhibitor floor', cost: 65, fun: 30, social: 20, durationMinutes: 300 },
      { label: 'Celebrity panel', cost: 0, fun: 22, social: 10, durationMinutes: 75 },
      { label: 'Artist alley commission', cost: 40, fun: 15, social: 10, durationMinutes: 30 },
      { label: 'Tabletop gaming room', cost: 0, fun: 20, social: 18, durationMinutes: 120, skillId: 'gaming' },
    ],
    description: 'Three days of cosplay, panels, artist alley, and lines for a photo with an actor from a show that ended in 2014.',
    crowd: 0.85,
    tags: ['geek', 'costume'],
  }),
  homecoming_game: F({
    id: 'homecoming_game',
    name: 'Homecoming Game',
    month: 10,
    venues: ['school', 'college', 'stadium', 'sports_field'],
    durationDays: 1,
    ticketPrice: 10,
    activities: [
      { label: 'Friday night lights', cost: 10, fun: 22, social: 22, durationMinutes: 180 },
      { label: 'Tailgate', cost: 25, fun: 20, social: 25, durationMinutes: 120 },
      { label: 'Homecoming parade', cost: 0, fun: 12, social: 15, durationMinutes: 60 },
    ],
    description: 'The band, the court, the parade down Main Street, and the whole town in the bleachers.',
    crowd: 0.8,
    tags: ['sport', 'school', 'fall'],
  }),
  diwali_festival: F({
    id: 'diwali_festival',
    name: 'Diwali Festival of Lights',
    month: 11,
    venues: ['community_center', 'park', 'college'],
    durationDays: 1,
    ticketPrice: 5,
    activities: [
      { label: 'Bollywood dance stage', cost: 0, fun: 24, social: 20, durationMinutes: 90, skillId: 'dancing' },
      { label: 'Chaat, samosas and jalebi', cost: 18, fun: 16, social: 10, durationMinutes: 45 },
      { label: 'Fireworks finale', cost: 0, fun: 22, social: 15, durationMinutes: 30 },
    ],
    description: 'Dance performances, rangoli, a mela of food stalls, and a fireworks finale.',
    crowd: 0.7,
    tags: ['cultural', 'food'],
  }),
  christmas_tree_lighting: F({
    id: 'christmas_tree_lighting',
    name: 'Christmas Tree Lighting',
    month: 12,
    venues: ['park', 'city_hall', 'mall'],
    durationDays: 1,
    ticketPrice: 0,
    activities: [
      { label: 'Countdown to the lights', cost: 0, fun: 20, social: 18, durationMinutes: 90 },
      { label: 'Hot chocolate and carolers', cost: 6, fun: 10, social: 10, durationMinutes: 30 },
      { label: 'Photo with Santa', cost: 25, fun: 12, social: 8, durationMinutes: 30 },
    ],
    description: 'The mayor flips a switch, a school choir sings, and kids line up for Santa.',
    crowd: 0.7,
    tags: ['winter', 'family', 'free'],
  }),
  holiday_market: F({
    id: 'holiday_market',
    name: 'Holiday Market',
    month: 12,
    venues: ['park', 'mall', 'community_center', 'farmers_market'],
    durationDays: 21,
    ticketPrice: 0,
    activities: [
      { label: 'Shop the artisan stalls', cost: 60, fun: 15, social: 12, durationMinutes: 75 },
      { label: 'Mulled wine and a bratwurst', cost: 15, fun: 12, social: 12, durationMinutes: 40 },
      { label: 'Ornament-making workshop', cost: 20, fun: 16, social: 10, durationMinutes: 60, skillId: 'crafting' },
    ],
    description: 'Wooden stalls, string lights, mulled wine, candles that cost too much, and a brass quartet.',
    crowd: 0.6,
    tags: ['winter', 'shopping'],
  }),
  night_market: F({
    id: 'night_market',
    name: 'Night Market',
    month: 6,
    venues: ['park', 'parking', 'mall', 'farmers_market'],
    durationDays: 2,
    ticketPrice: 5,
    activities: [
      { label: 'Skewers, boba and takoyaki', cost: 24, fun: 20, social: 12, durationMinutes: 60 },
      { label: 'Browse the vendors and neon art', cost: 30, fun: 14, social: 12, durationMinutes: 60 },
      { label: 'Late-night DJ set', cost: 0, fun: 20, social: 20, durationMinutes: 90, skillId: 'dancing' },
    ],
    description: 'Asian-night-market style: hundreds of vendors, neon, skewers on the grill, and a DJ until 1am.',
    crowd: 0.85,
    tags: ['food', 'nightlife', 'summer'],
  }),
};

export const FESTIVAL_IDS = Object.keys(FESTIVALS);
