/**
 * Hobby catalog. A sim can hold up to 6 hobbies (`sim.hobbies`).
 * `objects` enable the hobby at home (object def ids from content/objects.ts);
 * `venues` are archetypes where it can be pursued. Numbers are per typical session.
 * `stress` negative = relaxing. `costPerSession` in US dollars at cost-of-living 1.0.
 */
import type { HobbyDef } from './types';

const h = (d: HobbyDef): HobbyDef => d;

export const HOBBIES: Record<string, HobbyDef> = {
  running: h({ id: 'running', name: 'Running', icon: 'run', skillId: 'athletics', objects: ['treadmill'], venues: ['park', 'trail', 'gym', 'home', 'beach', 'sports_field'], costPerSession: 0, fun: 12, social: 2, fitness: 1.2, stress: -8, description: 'Lace up and go. Free, anywhere, any time — a 30-minute jog clears the head.' }),
  cycling: h({ id: 'cycling', name: 'Cycling', icon: 'bike', skillId: 'athletics', objects: ['exercise_bike', 'bike_rack'], venues: ['park', 'trail', 'gym', 'home'], costPerSession: 0, fun: 14, social: 4, fitness: 1.1, stress: -8, description: 'Road or trail. Doubles as a commute if you are brave about traffic.' }),
  hiking: h({ id: 'hiking', name: 'Hiking', icon: 'mountain', skillId: 'athletics', objects: [], venues: ['trail', 'park'], costPerSession: 0, fun: 18, social: 6, fitness: 0.9, stress: -12, description: 'Long walks somewhere green. Best in spring and fall; brutal in a Texas August.', seasonal: ['spring', 'fall', 'winter'] }),
  yoga: h({ id: 'yoga', name: 'Yoga', icon: 'lotus', skillId: 'fitness', objects: ['yoga_mat'], venues: ['yoga', 'gym', 'home', 'park', 'community_center'], costPerSession: 18, fun: 8, social: 4, fitness: 0.6, stress: -15, description: 'Stretch, breathe, and stop doom-scrolling for an hour. Drop-in classes run $15–25.' }),
  gym: h({ id: 'gym', name: 'Gym', icon: 'dumbbell', skillId: 'fitness', objects: ['weight_bench', 'dumbbells', 'treadmill', 'punching_bag'], venues: ['gym', 'home', 'climbing_gym', 'martial_arts'], costPerSession: 0, fun: 8, social: 5, fitness: 1.5, stress: -6, description: 'Lift, sweat, repeat. Memberships run $10–80/month; the home version needs equipment.' }),
  cooking: h({ id: 'cooking', name: 'Cooking', icon: 'chef-hat', skillId: 'cooking', objects: ['stove', 'oven', 'air_fryer', 'grill'], venues: ['home', 'community_center'], costPerSession: 12, fun: 12, social: 6, stress: -6, description: 'Real meals from real groceries. Saves money over takeout once you stop burning things.' }),
  baking: h({ id: 'baking', name: 'Baking', icon: 'cake', skillId: 'baking', objects: ['oven'], venues: ['home'], costPerSession: 8, fun: 12, social: 5, stress: -8, description: 'Bread, cookies, the occasional disaster cake. Neighbors love a baker.' }),
  gardening: h({ id: 'gardening', name: 'Gardening', icon: 'sprout', skillId: 'gardening', objects: ['garden_bed', 'planter', 'houseplant'], venues: ['home', 'community_center', 'park'], costPerSession: 5, fun: 10, social: 2, fitness: 0.3, stress: -12, description: 'Dirt under the nails and tomatoes in August. Cheaper than therapy, slower than groceries.', seasonal: ['spring', 'summer', 'fall'] }),
  reading: h({ id: 'reading', name: 'Reading', icon: 'book', skillId: 'research', objects: ['bookshelf', 'armchair', 'reading_nook'], venues: ['home', 'library', 'cafe', 'park', 'bookstore'], costPerSession: 0, fun: 12, social: 0, stress: -10, description: 'A book, a chair, silence. Library cards are free.' }),
  writing: h({ id: 'writing', name: 'Writing', icon: 'pen', skillId: 'writing', objects: ['desk', 'laptop', 'computer'], venues: ['home', 'cafe', 'library', 'coworking'], costPerSession: 0, fun: 9, social: 0, stress: -7, description: 'Journal, fiction, the novel you keep mentioning. A notebook is enough to start.' }),
  painting: h({ id: 'painting', name: 'Painting', icon: 'palette', skillId: 'painting', objects: ['easel'], venues: ['home', 'art_studio', 'park'], costPerSession: 10, fun: 14, social: 1, stress: -12, description: 'Canvas or sketchbook. Supplies cost; peace of mind is free.' }),
  photography: h({ id: 'photography', name: 'Photography', icon: 'camera', skillId: 'photography', objects: [], venues: ['park', 'trail', 'beach', 'museum', 'zoo', 'home', 'farmers_market'], costPerSession: 0, fun: 12, social: 3, fitness: 0.2, stress: -8, description: 'Chasing light with a phone or a camera. Golden hour is free.' }),
  guitar: h({ id: 'guitar', name: 'Guitar', icon: 'guitar', skillId: 'guitar', objects: ['guitar'], venues: ['home', 'music_school', 'park'], costPerSession: 0, fun: 14, social: 3, stress: -9, description: 'Four chords, sore fingertips, and eventually a song. Needs a guitar.' }),
  piano: h({ id: 'piano', name: 'Piano', icon: 'piano', skillId: 'piano', objects: ['piano', 'keyboard'], venues: ['home', 'music_school', 'church'], costPerSession: 0, fun: 13, social: 2, stress: -10, description: 'Scales, then songs. A cheap keyboard works fine.' }),
  singing: h({ id: 'singing', name: 'Singing', icon: 'mic', skillId: 'singing', objects: ['karaoke_machine', 'bluetooth_speaker', 'shower'], venues: ['home', 'bar', 'church', 'music_school', 'nightclub'], costPerSession: 0, fun: 14, social: 8, stress: -9, description: 'Shower, car, choir, karaoke. Anywhere with a beat and no shame.' }),
  gaming: h({ id: 'gaming', name: 'Gaming', icon: 'gamepad', skillId: 'gaming', objects: ['gaming_console', 'computer', 'laptop', 'tv'], venues: ['home', 'arcade'], costPerSession: 0, fun: 18, social: 5, stress: -5, description: 'Console, PC, or the arcade. Fun spikes; energy and daylight do not.' }),
  board_games: h({ id: 'board_games', name: 'Board Games', icon: 'dice', skillId: 'logic', objects: ['board_games', 'dining_table', 'puzzle'], venues: ['home', 'cafe', 'library', 'community_center', 'bar'], costPerSession: 0, fun: 16, social: 14, stress: -8, description: 'Catan, cards, or a 1,000-piece puzzle. Best with people.' }),
  chess: h({ id: 'chess', name: 'Chess', icon: 'crown', skillId: 'logic', objects: ['chess_set', 'computer', 'laptop'], venues: ['home', 'park', 'library', 'cafe', 'community_center'], costPerSession: 0, fun: 10, social: 8, stress: -4, description: 'Park benches and phone apps. Losing is educational.' }),
  fishing: h({ id: 'fishing', name: 'Fishing', icon: 'fish', skillId: 'fishing', objects: [], venues: ['park', 'beach', 'trail'], costPerSession: 6, fun: 12, social: 5, fitness: 0.1, stress: -15, description: 'A line in the water and nowhere to be. A license runs ~$30/year; bait is a few bucks.' }),
  camping: h({ id: 'camping', name: 'Camping', icon: 'tent', skillId: 'handiness', objects: ['fire_pit'], venues: ['trail', 'park', 'beach'], costPerSession: 30, fun: 20, social: 12, fitness: 0.5, stress: -18, description: 'A tent, a fire, and no cell service. State park sites run $15–40 a night.', seasonal: ['spring', 'summer', 'fall'] }),
  woodworking: h({ id: 'woodworking', name: 'Woodworking', icon: 'hammer', skillId: 'crafting', objects: ['workbench', 'tool_chest'], venues: ['home', 'community_center'], costPerSession: 15, fun: 12, social: 1, fitness: 0.3, stress: -10, description: 'Sawdust, measuring twice, and furniture that is almost level. Lumber is not cheap.' }),
  knitting: h({ id: 'knitting', name: 'Knitting', icon: 'yarn', skillId: 'crafting', objects: ['sofa', 'armchair'], venues: ['home', 'cafe', 'library', 'senior_center', 'community_center'], costPerSession: 6, fun: 9, social: 4, stress: -12, description: 'Scarves for everyone you know. Calming, portable, yarn adds up.' }),
  birdwatching: h({ id: 'birdwatching', name: 'Birdwatching', icon: 'bird', skillId: 'research', objects: ['telescope'], venues: ['park', 'trail', 'beach', 'home'], costPerSession: 0, fun: 9, social: 3, fitness: 0.3, stress: -14, description: 'Binoculars, a checklist, and unreasonable excitement about a warbler.' }),
  dancing: h({ id: 'dancing', name: 'Dancing', icon: 'dance', skillId: 'dancing', objects: ['stereo', 'bluetooth_speaker'], venues: ['dance_studio', 'nightclub', 'bar', 'home', 'community_center'], costPerSession: 15, fun: 18, social: 14, fitness: 0.7, stress: -10, description: 'Salsa class, two-step night, or the kitchen at midnight. Classes run $10–20.' }),
  karaoke: h({ id: 'karaoke', name: 'Karaoke', icon: 'mic-2', skillId: 'singing', objects: ['karaoke_machine'], venues: ['bar', 'nightclub', 'home'], costPerSession: 20, fun: 20, social: 16, stress: -8, description: 'Bad songs, sung loud, with friends. Bar tab included in the price.' }),
  bowling: h({ id: 'bowling', name: 'Bowling', icon: 'circle', skillId: 'athletics', objects: [], venues: ['bowling'], costPerSession: 22, fun: 16, social: 14, fitness: 0.2, stress: -8, description: 'Rented shoes and cheap pitchers. $5–8 a game plus shoes; league night is cheaper.' }),
  basketball: h({ id: 'basketball', name: 'Basketball', icon: 'basketball', skillId: 'athletics', objects: [], venues: ['park', 'gym', 'sports_field', 'community_center', 'school'], costPerSession: 0, fun: 16, social: 14, fitness: 1.3, stress: -8, description: 'Pickup at the park. Free, sweaty, and a fast way to meet people.' }),
  soccer: h({ id: 'soccer', name: 'Soccer', icon: 'soccer', skillId: 'athletics', objects: [], venues: ['park', 'sports_field', 'school', 'community_center'], costPerSession: 0, fun: 16, social: 14, fitness: 1.4, stress: -8, description: 'Rec league or pickup. Cleats optional, cardio mandatory.' }),
  golf: h({ id: 'golf', name: 'Golf', icon: 'flag', skillId: 'athletics', objects: [], venues: ['golf'], costPerSession: 45, fun: 14, social: 12, fitness: 0.5, stress: -8, description: 'Eighteen holes and four hours. Municipal courses are $25–60; private is another world.', seasonal: ['spring', 'summer', 'fall'] }),
  volunteering: h({ id: 'volunteering', name: 'Volunteering', icon: 'hand-heart', skillId: 'charisma', objects: [], venues: ['shelter', 'church', 'community_center', 'senior_center', 'library', 'park', 'school'], costPerSession: 0, fun: 8, social: 14, stress: -6, description: 'Food bank shifts, shelter walks, park cleanups. Good for the soul and the reputation.' }),
  thrifting: h({ id: 'thrifting', name: 'Thrifting', icon: 'shirt', skillId: 'negotiation', objects: [], venues: ['thrift_store', 'farmers_market', 'mall'], costPerSession: 15, fun: 14, social: 4, fitness: 0.2, stress: -6, description: 'Hunting racks for the perfect vintage jacket. Cheap thrills, occasional treasure.' }),
  podcasting: h({ id: 'podcasting', name: 'Podcasting', icon: 'radio', skillId: 'charisma', objects: ['computer', 'laptop'], venues: ['home', 'coworking'], costPerSession: 0, fun: 10, social: 8, stress: -3, description: 'A mic, a friend, and opinions. Everyone has one; a few even get listeners.' }),
  streaming: h({ id: 'streaming', name: 'Streaming', icon: 'video', skillId: 'gaming', objects: ['computer', 'gaming_console'], venues: ['home'], costPerSession: 0, fun: 14, social: 8, stress: 2, description: 'Playing games for an audience that may or may not exist. Late nights, occasional tips.' }),
  collecting: h({ id: 'collecting', name: 'Collecting', icon: 'package', skillId: 'research', objects: ['bookshelf', 'record_player'], venues: ['home', 'thrift_store', 'farmers_market', 'bookstore', 'mall'], costPerSession: 20, fun: 12, social: 3, stress: -6, description: 'Records, cards, sneakers, coins. The hunt is the hobby; the shelf is the proof.' }),
};

export const HOBBY_IDS = Object.keys(HOBBIES);
