/**
 * Illness catalog. Modeled by systems/health.ts.
 *
 * Lifecycle (non-chronic): severity starts at a def-specific value, rises by `progression`
 * per day for the first half of `baseDurationDays`, then falls naturally at 100/baseDurationDays
 * per day (faster with treatment). Lethal illnesses kill at severity 100 — lethal + high
 * progression means "gets you before it resolves" (appendicitis, heart attack) unless treated.
 * Chronic: never resolves; treatment keeps severity managed (~15), untreated it creeps up.
 *
 * `incidence` = baseline chance per sim per DAY of spontaneous onset (before modifiers).
 * 0 = only via events (injuries, exposure, pregnancy, alcohol…).
 * `effects` are per full day at severity 50; scaled by severity and elapsed time.
 * Treatment `cost` is the sticker price before insurance (US 2020s ballpark).
 */
import type { IllnessDef } from './types';

const d = (x: IllnessDef): IllnessDef => x;

export const ILLNESSES: Record<string, IllnessDef> = {
  common_cold: d({
    id: 'common_cold',
    name: 'Common cold',
    description: 'Runny nose, sore throat, a week of feeling 80%. Everyone gets two or three a year.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 7,
    chronic: false,
    incidence: 0.007,
    seasonal: ['fall', 'winter'],
    effects: { energy: -12, comfort: -10, fun: -4, stress: 2 },
    progression: 5,
    treatments: [
      { label: 'Cold medicine', venue: 'home', cost: 12, effectiveness: 0.3, itemId: 'cold_medicine' },
      { label: 'Rest and fluids', venue: 'home', cost: 0, effectiveness: 0.2 },
      { label: 'Urgent care', venue: 'clinic', cost: 150, effectiveness: 0.35 },
    ],
    lethal: false,
    symptoms: ['runny nose', 'sore throat', 'sneezing', 'mild cough'],
  }),
  flu: d({
    id: 'flu',
    name: 'Flu',
    description: 'Fever, aches, and three days flat on your back. A flu shot cuts the odds sharply.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 9,
    chronic: false,
    incidence: 0.0025,
    seasonal: ['winter', 'fall'],
    effects: { energy: -30, comfort: -25, fun: -10, stress: 5, hunger: 4, health: -1 },
    progression: 10,
    treatments: [
      { label: 'Antivirals (Tamiflu)', venue: 'clinic', cost: 200, effectiveness: 0.5 },
      { label: 'Cold & flu medicine', venue: 'home', cost: 12, effectiveness: 0.25, itemId: 'cold_medicine' },
      { label: 'Urgent care', venue: 'clinic', cost: 150, effectiveness: 0.4 },
    ],
    lethal: true,
    symptoms: ['fever', 'body aches', 'chills', 'fatigue', 'cough'],
  }),
  covid: d({
    id: 'covid',
    name: 'COVID-19',
    description: 'Still around. Fatigue, cough, loss of taste. Contagious before you feel it.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 10,
    chronic: false,
    incidence: 0.002,
    seasonal: ['winter', 'summer'],
    effects: { energy: -25, comfort: -18, fun: -10, stress: 6, health: -1 },
    progression: 9,
    treatments: [
      { label: 'Paxlovid', venue: 'clinic', cost: 250, effectiveness: 0.5 },
      { label: 'Rest and OTC meds', venue: 'home', cost: 12, effectiveness: 0.25, itemId: 'cold_medicine' },
      { label: 'Hospital care', venue: 'hospital', cost: 3500, effectiveness: 0.7 },
    ],
    lethal: true,
    symptoms: ['cough', 'fatigue', 'fever', 'loss of taste', 'shortness of breath'],
  }),
  strep_throat: d({
    id: 'strep_throat',
    name: 'Strep throat',
    description: 'A throat that feels like glass. Antibiotics fix it in days; untreated it drags on.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 8,
    chronic: false,
    incidence: 0.0012,
    seasonal: ['winter', 'spring'],
    effects: { energy: -12, comfort: -22, hunger: -6, stress: 3 },
    progression: 8,
    treatments: [
      { label: 'Antibiotics', venue: 'clinic', cost: 200, effectiveness: 0.8, itemId: 'antibiotics' },
      { label: 'Urgent care + antibiotics', venue: 'clinic', cost: 180, effectiveness: 0.8 },
    ],
    lethal: false,
    symptoms: ['severe sore throat', 'fever', 'swollen glands', 'painful swallowing'],
  }),
  stomach_bug: d({
    id: 'stomach_bug',
    name: 'Stomach bug',
    description: 'Norovirus or similar. Two miserable days near a bathroom.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 3,
    chronic: false,
    incidence: 0.002,
    seasonal: ['winter'],
    effects: { energy: -20, comfort: -30, hunger: -10, fun: -12, stress: 5 },
    progression: 15,
    treatments: [
      { label: 'Antacid & fluids', venue: 'home', cost: 8, effectiveness: 0.25, itemId: 'antacid' },
      { label: 'Urgent care (IV fluids)', venue: 'clinic', cost: 220, effectiveness: 0.45 },
    ],
    lethal: false,
    symptoms: ['nausea', 'vomiting', 'diarrhea', 'cramps'],
  }),
  food_poisoning: d({
    id: 'food_poisoning',
    name: 'Food poisoning',
    description: 'That chicken was not fine. Hits 6–24 hours after the meal, gone in a day or two.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 2,
    chronic: false,
    incidence: 0.0008,
    effects: { energy: -18, comfort: -32, hunger: -12, fun: -10, stress: 6 },
    progression: 20,
    treatments: [
      { label: 'Antacid & fluids', venue: 'home', cost: 8, effectiveness: 0.3, itemId: 'antacid' },
      { label: 'Urgent care', venue: 'clinic', cost: 180, effectiveness: 0.5 },
    ],
    lethal: false,
    symptoms: ['nausea', 'vomiting', 'stomach cramps', 'chills'],
  }),
  seasonal_allergies: d({
    id: 'seasonal_allergies',
    name: 'Seasonal allergies',
    description: 'Cedar, oak, ragweed — whatever is blooming. Itchy eyes for weeks.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 21,
    chronic: false,
    incidence: 0.004,
    seasonal: ['spring', 'fall'],
    effects: { energy: -6, comfort: -10, fun: -4, stress: 1 },
    progression: 2,
    treatments: [
      { label: 'Allergy meds', venue: 'home', cost: 15, effectiveness: 0.6, itemId: 'allergy_meds' },
      { label: 'Allergy shots', venue: 'clinic', cost: 300, effectiveness: 0.8 },
    ],
    lethal: false,
    symptoms: ['sneezing', 'itchy eyes', 'congestion'],
  }),
  migraine: d({
    id: 'migraine',
    name: 'Migraine',
    description: 'Light hurts, sound hurts, thinking hurts. A dark room and hours.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 1,
    chronic: false,
    incidence: 0.003,
    effects: { energy: -15, comfort: -35, fun: -20, stress: 8 },
    progression: 30,
    treatments: [
      { label: 'Painkillers', venue: 'home', cost: 8, effectiveness: 0.4, itemId: 'painkillers' },
      { label: 'Prescription triptans', venue: 'pharmacy', cost: 60, effectiveness: 0.7, itemId: 'prescription_meds' },
    ],
    lethal: false,
    symptoms: ['throbbing headache', 'light sensitivity', 'nausea'],
  }),
  back_pain: d({
    id: 'back_pain',
    name: 'Back pain',
    description: 'Lifted wrong, slept wrong, or just turned 35. Chairs become enemies.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 10,
    chronic: false,
    incidence: 0.0015,
    effects: { energy: -8, comfort: -22, fun: -5, stress: 4 },
    progression: 4,
    treatments: [
      { label: 'Painkillers & rest', venue: 'home', cost: 8, effectiveness: 0.3, itemId: 'painkillers' },
      { label: 'Physical therapy', venue: 'clinic', cost: 120, effectiveness: 0.6 },
      { label: 'Massage', venue: 'spa', cost: 90, effectiveness: 0.35 },
    ],
    lethal: false,
    symptoms: ['lower back ache', 'stiffness', 'pain when bending'],
  }),
  sprained_ankle: d({
    id: 'sprained_ankle',
    name: 'Sprained ankle',
    description: 'Rolled it on a curb. Swollen, purple, and slow for a couple weeks.',
    kind: 'injury',
    contagious: false,
    baseDurationDays: 14,
    chronic: false,
    incidence: 0,
    effects: { energy: -6, comfort: -18, fun: -6, stress: 3 },
    progression: 2,
    treatments: [
      { label: 'RICE & painkillers', venue: 'home', cost: 8, effectiveness: 0.35, itemId: 'painkillers' },
      { label: 'Urgent care (X-ray, brace)', venue: 'clinic', cost: 350, effectiveness: 0.6 },
    ],
    lethal: false,
    symptoms: ['swollen ankle', 'limping', 'bruising'],
  }),
  broken_arm: d({
    id: 'broken_arm',
    name: 'Broken arm',
    description: 'A cast for six weeks and a lot of one-handed everything.',
    kind: 'injury',
    contagious: false,
    baseDurationDays: 42,
    chronic: false,
    incidence: 0,
    effects: { energy: -6, comfort: -20, fun: -10, stress: 6 },
    progression: 1,
    treatments: [
      { label: 'ER (X-ray, cast)', venue: 'hospital', cost: 2500, effectiveness: 0.8 },
      { label: 'Urgent care (splint, referral)', venue: 'clinic', cost: 400, effectiveness: 0.5 },
    ],
    lethal: false,
    symptoms: ['arm in a cast', 'pain', 'limited movement'],
  }),
  concussion: d({
    id: 'concussion',
    name: 'Concussion',
    description: 'Hit your head. Fog, headaches, no screens for a while.',
    kind: 'injury',
    contagious: false,
    baseDurationDays: 12,
    chronic: false,
    incidence: 0,
    effects: { energy: -15, comfort: -20, fun: -15, stress: 8, health: -1 },
    progression: 5,
    treatments: [
      { label: 'ER evaluation (CT scan)', venue: 'hospital', cost: 1800, effectiveness: 0.6 },
      { label: 'Rest in the dark', venue: 'home', cost: 0, effectiveness: 0.25 },
    ],
    lethal: true,
    symptoms: ['headache', 'dizziness', 'confusion', 'nausea'],
  }),
  sunburn: d({
    id: 'sunburn',
    name: 'Sunburn',
    description: 'Forgot the sunscreen. Red, hot, and everything touches it.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 3,
    chronic: false,
    incidence: 0,
    seasonal: ['summer'],
    effects: { comfort: -20, fun: -4, energy: -4 },
    progression: 10,
    treatments: [{ label: 'Aloe & painkillers', venue: 'home', cost: 8, effectiveness: 0.4, itemId: 'painkillers' }],
    lethal: false,
    symptoms: ['red skin', 'peeling', 'tenderness'],
  }),
  heat_exhaustion: d({
    id: 'heat_exhaustion',
    name: 'Heat exhaustion',
    description: 'Too long outside in 100° heat. Dizzy, drenched, and dangerously close to heat stroke.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 1,
    chronic: false,
    incidence: 0,
    seasonal: ['summer'],
    effects: { energy: -35, comfort: -30, stress: 10, health: -3 },
    progression: 40,
    treatments: [
      { label: 'Cool down & hydrate', venue: 'home', cost: 0, effectiveness: 0.6 },
      { label: 'ER (IV fluids)', venue: 'hospital', cost: 1500, effectiveness: 0.9 },
    ],
    lethal: true,
    symptoms: ['dizziness', 'heavy sweating', 'nausea', 'rapid pulse'],
  }),
  hypothermia: d({
    id: 'hypothermia',
    name: 'Hypothermia',
    description: 'Too cold for too long. Shivering stops being the worst part.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 1,
    chronic: false,
    incidence: 0,
    seasonal: ['winter'],
    effects: { energy: -35, comfort: -35, stress: 10, health: -4 },
    progression: 45,
    treatments: [
      { label: 'Warm up indoors', venue: 'home', cost: 0, effectiveness: 0.6 },
      { label: 'ER', venue: 'hospital', cost: 1500, effectiveness: 0.9 },
    ],
    lethal: true,
    symptoms: ['shivering', 'confusion', 'numb hands', 'slurred speech'],
  }),
  dehydration: d({
    id: 'dehydration',
    name: 'Dehydration',
    description: 'Headache, cramps, dark urine. Water fixes it; ignoring it does not.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 1,
    chronic: false,
    incidence: 0,
    effects: { energy: -20, comfort: -20, stress: 5, health: -2 },
    progression: 30,
    treatments: [
      { label: 'Drink water', venue: 'home', cost: 0, effectiveness: 0.7 },
      { label: 'Urgent care (IV)', venue: 'clinic', cost: 250, effectiveness: 0.9 },
    ],
    lethal: true,
    symptoms: ['headache', 'dry mouth', 'dizziness', 'fatigue'],
  }),
  uti: d({
    id: 'uti',
    name: 'UTI',
    description: 'Burning, urgency, misery. Antibiotics clear it fast; untreated it can climb to the kidneys.',
    kind: 'infection',
    contagious: false,
    baseDurationDays: 7,
    chronic: false,
    incidence: 0.0012,
    effects: { comfort: -25, energy: -8, stress: 5 },
    progression: 8,
    treatments: [
      { label: 'Antibiotics', venue: 'clinic', cost: 200, effectiveness: 0.85, itemId: 'antibiotics' },
      { label: 'Cranberry & water', venue: 'home', cost: 5, effectiveness: 0.15 },
    ],
    lethal: false,
    symptoms: ['burning urination', 'urgency', 'lower abdominal pain'],
  }),
  ear_infection: d({
    id: 'ear_infection',
    name: 'Ear infection',
    description: 'Throbbing ear, muffled hearing. Common in kids; adults get it after a cold.',
    kind: 'infection',
    contagious: false,
    baseDurationDays: 7,
    chronic: false,
    incidence: 0.0008,
    seasonal: ['winter'],
    effects: { comfort: -20, energy: -6, fun: -6, stress: 3 },
    progression: 6,
    treatments: [
      { label: 'Antibiotics', venue: 'clinic', cost: 200, effectiveness: 0.7, itemId: 'antibiotics' },
      { label: 'Painkillers', venue: 'home', cost: 8, effectiveness: 0.25, itemId: 'painkillers' },
    ],
    lethal: false,
    symptoms: ['ear pain', 'muffled hearing', 'fever'],
  }),
  bronchitis: d({
    id: 'bronchitis',
    name: 'Bronchitis',
    description: 'The cough that follows a cold and stays for weeks.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 16,
    chronic: false,
    incidence: 0.001,
    seasonal: ['winter', 'fall'],
    effects: { energy: -14, comfort: -14, fun: -5, stress: 3 },
    progression: 4,
    treatments: [
      { label: 'Doctor visit (inhaler, cough meds)', venue: 'clinic', cost: 200, effectiveness: 0.5 },
      { label: 'Cold medicine & rest', venue: 'home', cost: 12, effectiveness: 0.2, itemId: 'cold_medicine' },
    ],
    lethal: false,
    symptoms: ['persistent cough', 'chest tightness', 'wheezing'],
  }),
  pneumonia: d({
    id: 'pneumonia',
    name: 'Pneumonia',
    description: 'Lung infection. Fever, chest pain, and real danger for the old or run-down.',
    kind: 'infection',
    contagious: true,
    baseDurationDays: 21,
    chronic: false,
    incidence: 0.0004,
    seasonal: ['winter'],
    effects: { energy: -30, comfort: -25, fun: -10, stress: 8, health: -2 },
    progression: 6,
    treatments: [
      { label: 'Antibiotics', venue: 'clinic', cost: 250, effectiveness: 0.7, itemId: 'antibiotics' },
      { label: 'Hospital admission', venue: 'hospital', cost: 9000, effectiveness: 0.9 },
    ],
    lethal: true,
    symptoms: ['fever', 'chest pain', 'productive cough', 'shortness of breath'],
  }),
  asthma: d({
    id: 'asthma',
    name: 'Asthma',
    description: 'Chronic. Manageable with an inhaler; flares with smoke, cold air, and exertion.',
    kind: 'chronic',
    contagious: false,
    baseDurationDays: 3650,
    chronic: true,
    incidence: 0.00008,
    effects: { energy: -5, comfort: -6, stress: 2 },
    progression: 0.2,
    treatments: [
      { label: 'Inhaler prescription', venue: 'pharmacy', cost: 60, effectiveness: 0.8, itemId: 'prescription_meds' },
      { label: 'Specialist visit', venue: 'clinic', cost: 250, effectiveness: 0.7 },
    ],
    lethal: true,
    symptoms: ['wheezing', 'shortness of breath', 'chest tightness'],
  }),
  diabetes_t2: d({
    id: 'diabetes_t2',
    name: 'Type 2 diabetes',
    description: 'Blood sugar the body can no longer regulate. Diet, weight, and metformin.',
    kind: 'chronic',
    contagious: false,
    baseDurationDays: 3650,
    chronic: true,
    incidence: 0.00012,
    effects: { energy: -8, comfort: -5, stress: 2, health: -0.3 },
    progression: 0.15,
    treatments: [
      { label: 'Metformin prescription', venue: 'pharmacy', cost: 25, effectiveness: 0.7, itemId: 'prescription_meds' },
      { label: 'Doctor visit & management plan', venue: 'clinic', cost: 220, effectiveness: 0.6 },
    ],
    lethal: true,
    symptoms: ['thirst', 'fatigue', 'frequent urination', 'blurred vision'],
  }),
  hypertension: d({
    id: 'hypertension',
    name: 'High blood pressure',
    description: 'Silent. No symptoms until the heart attack. Meds are cheap; the alternative is not.',
    kind: 'chronic',
    contagious: false,
    baseDurationDays: 3650,
    chronic: true,
    incidence: 0.0002,
    effects: { stress: 1, health: -0.2 },
    progression: 0.12,
    treatments: [
      { label: 'Blood pressure meds', venue: 'pharmacy', cost: 20, effectiveness: 0.75, itemId: 'prescription_meds' },
      { label: 'Doctor visit', venue: 'clinic', cost: 200, effectiveness: 0.6 },
    ],
    lethal: true,
    symptoms: ['none', 'occasional headaches'],
  }),
  high_cholesterol: d({
    id: 'high_cholesterol',
    name: 'High cholesterol',
    description: 'Found on a blood panel. Statins and fewer burgers.',
    kind: 'chronic',
    contagious: false,
    baseDurationDays: 3650,
    chronic: true,
    incidence: 0.00015,
    effects: { health: -0.15 },
    progression: 0.1,
    treatments: [
      { label: 'Statin prescription', venue: 'pharmacy', cost: 15, effectiveness: 0.7, itemId: 'prescription_meds' },
      { label: 'Doctor visit', venue: 'clinic', cost: 200, effectiveness: 0.5 },
    ],
    lethal: false,
    symptoms: ['none'],
  }),
  depression: d({
    id: 'depression',
    name: 'Depression',
    description: 'Not sadness — absence. Nothing is fun, everything is heavy, getting up is work.',
    kind: 'mental',
    contagious: false,
    baseDurationDays: 120,
    chronic: false,
    incidence: 0.0001,
    effects: { energy: -12, fun: -18, stress: 6, hunger: 2 },
    progression: 1.5,
    treatments: [
      { label: 'Therapy', venue: 'clinic', cost: 150, effectiveness: 0.6 },
      { label: 'Antidepressants', venue: 'pharmacy', cost: 30, effectiveness: 0.55, itemId: 'prescription_meds' },
    ],
    lethal: false,
    symptoms: ['low mood', 'no interest', 'fatigue', 'sleep changes'],
  }),
  anxiety: d({
    id: 'anxiety',
    name: 'Anxiety disorder',
    description: 'Worry that does not switch off. Racing heart, bad sleep, dread with no address.',
    kind: 'mental',
    contagious: false,
    baseDurationDays: 90,
    chronic: false,
    incidence: 0.00012,
    effects: { energy: -8, comfort: -8, stress: 10 },
    progression: 1.5,
    treatments: [
      { label: 'Therapy (CBT)', venue: 'clinic', cost: 150, effectiveness: 0.6 },
      { label: 'SSRIs', venue: 'pharmacy', cost: 30, effectiveness: 0.5, itemId: 'prescription_meds' },
    ],
    lethal: false,
    symptoms: ['restlessness', 'racing thoughts', 'trouble sleeping', 'tension'],
  }),
  insomnia: d({
    id: 'insomnia',
    name: 'Insomnia',
    description: 'Can\'t fall asleep, can\'t stay asleep. Days blur.',
    kind: 'mental',
    contagious: false,
    baseDurationDays: 30,
    chronic: false,
    incidence: 0.0002,
    effects: { energy: -20, comfort: -6, stress: 6, fun: -4 },
    progression: 2,
    treatments: [
      { label: 'Sleep hygiene & melatonin', venue: 'home', cost: 10, effectiveness: 0.35 },
      { label: 'Doctor visit (sleep meds)', venue: 'clinic', cost: 200, effectiveness: 0.6 },
    ],
    lethal: false,
    symptoms: ['trouble sleeping', 'daytime fatigue', 'irritability'],
  }),
  burnout: d({
    id: 'burnout',
    name: 'Burnout',
    description: 'Months of stress with no off switch. Cynical, exhausted, and done.',
    kind: 'mental',
    contagious: false,
    baseDurationDays: 45,
    chronic: false,
    incidence: 0,
    effects: { energy: -15, fun: -15, stress: 8, comfort: -4 },
    progression: 2,
    treatments: [
      { label: 'Time off & therapy', venue: 'clinic', cost: 150, effectiveness: 0.6 },
      { label: 'Vacation', venue: 'home', cost: 0, effectiveness: 0.4 },
    ],
    lethal: false,
    symptoms: ['exhaustion', 'cynicism', 'dread of work', 'poor focus'],
  }),
  appendicitis: d({
    id: 'appendicitis',
    name: 'Appendicitis',
    description: 'Sharp pain, lower right. Surgery within a day or two, or it ruptures.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 6,
    chronic: false,
    incidence: 0.00003,
    effects: { energy: -25, comfort: -45, hunger: -15, stress: 15, health: -6 },
    progression: 35,
    treatments: [
      { label: 'Emergency appendectomy', venue: 'hospital', cost: 18000, effectiveness: 0.95 },
    ],
    lethal: true,
    symptoms: ['sharp lower-right abdominal pain', 'fever', 'nausea', 'loss of appetite'],
  }),
  heart_attack: d({
    id: 'heart_attack',
    name: 'Heart attack',
    description: 'Crushing chest pain, arm numbness, cold sweat. Minutes matter.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 2,
    chronic: false,
    incidence: 0.00002,
    effects: { energy: -40, comfort: -50, stress: 25, health: -20 },
    progression: 120,
    treatments: [
      { label: 'ER / cardiac care', venue: 'hospital', cost: 45000, effectiveness: 0.9 },
    ],
    lethal: true,
    symptoms: ['chest pain', 'arm numbness', 'shortness of breath', 'cold sweat'],
  }),
  cancer: d({
    id: 'cancer',
    name: 'Cancer',
    description: 'Rare, slow, and life-altering. Treatment is long and expensive; outcomes depend on catching it early.',
    kind: 'chronic',
    contagious: false,
    baseDurationDays: 730,
    chronic: true,
    incidence: 0.000015,
    effects: { energy: -12, comfort: -10, fun: -8, stress: 8, health: -0.8, hunger: 2 },
    progression: 0.25,
    treatments: [
      { label: 'Oncology (chemo/radiation)', venue: 'hospital', cost: 12000, effectiveness: 0.7 },
      { label: 'Surgery', venue: 'hospital', cost: 35000, effectiveness: 0.8 },
    ],
    lethal: true,
    symptoms: ['fatigue', 'weight loss', 'pain', 'night sweats'],
  }),
  sti: d({
    id: 'sti',
    name: 'STI',
    description: 'Chlamydia or similar, from unprotected sex. Awkward clinic visit, easy antibiotics.',
    kind: 'infection',
    contagious: false,
    baseDurationDays: 21,
    chronic: false,
    incidence: 0,
    effects: { comfort: -10, stress: 8 },
    progression: 3,
    treatments: [
      { label: 'Clinic visit & antibiotics', venue: 'clinic', cost: 180, effectiveness: 0.9, itemId: 'antibiotics' },
    ],
    lethal: false,
    symptoms: ['discomfort', 'discharge', 'often none'],
  }),
  pregnancy_nausea: d({
    id: 'pregnancy_nausea',
    name: 'Morning sickness',
    description: 'First-trimester nausea that ignores the word "morning".',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 45,
    chronic: false,
    incidence: 0,
    effects: { energy: -8, comfort: -15, hunger: -4, fun: -4 },
    progression: 1,
    treatments: [
      { label: 'Ginger, crackers, rest', venue: 'home', cost: 5, effectiveness: 0.3 },
      { label: 'OB visit (anti-nausea meds)', venue: 'clinic', cost: 200, effectiveness: 0.6 },
    ],
    lethal: false,
    symptoms: ['nausea', 'food aversions', 'fatigue'],
  }),
  hangover: d({
    id: 'hangover',
    name: 'Hangover',
    description: 'Last night\'s decisions, invoiced. Headache, nausea, regret.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 1,
    chronic: false,
    incidence: 0,
    effects: { energy: -25, comfort: -25, fun: -8, stress: 6, hunger: 4 },
    progression: 30,
    treatments: [
      { label: 'Water, painkillers, greasy food', venue: 'home', cost: 8, effectiveness: 0.5, itemId: 'painkillers' },
    ],
    lethal: false,
    symptoms: ['headache', 'nausea', 'light sensitivity', 'regret'],
  }),
  tooth_decay: d({
    id: 'tooth_decay',
    name: 'Toothache',
    description: 'A cavity you ignored. Throbbing until the dentist drills it.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 30,
    chronic: false,
    incidence: 0.0005,
    effects: { comfort: -18, fun: -6, hunger: -3, stress: 4 },
    progression: 3,
    treatments: [
      { label: 'Dental filling', venue: 'dentist', cost: 250, effectiveness: 0.9 },
      { label: 'Painkillers', venue: 'home', cost: 8, effectiveness: 0.2, itemId: 'painkillers' },
    ],
    lethal: false,
    symptoms: ['toothache', 'sensitivity to cold', 'pain when chewing'],
  }),
  acid_reflux: d({
    id: 'acid_reflux',
    name: 'Acid reflux',
    description: 'Heartburn after every big meal. Antacids and smaller dinners.',
    kind: 'condition',
    contagious: false,
    baseDurationDays: 14,
    chronic: false,
    incidence: 0.001,
    effects: { comfort: -12, energy: -3 },
    progression: 2,
    treatments: [
      { label: 'Antacids', venue: 'home', cost: 8, effectiveness: 0.5, itemId: 'antacid' },
      { label: 'Doctor visit (PPI)', venue: 'clinic', cost: 200, effectiveness: 0.7 },
    ],
    lethal: false,
    symptoms: ['heartburn', 'sour taste', 'chest discomfort'],
  }),
};

export const ILLNESS_IDS = Object.keys(ILLNESSES);
