/**
 * Education programs — GED through professional degrees plus certifications & bootcamps.
 *
 * Tuition is per term at cost-of-living 1.0 (the education system scales it by region).
 * Terms are 16-week semesters unless noted (bootcamps run one 12-week term).
 * Programs whose id starts with `cert_` grant a certification (`education.certifications`)
 * instead of a degree.
 */
import type { SkillId } from '../core/types';
import type { ProgramDef } from './types';

type C = { name: string; skillId?: SkillId };
const c = (name: string, skillId?: SkillId): C => ({ name, skillId });

const program = (o: ProgramDef): ProgramDef => o;

export const PROGRAMS: Record<string, ProgramDef> = {
  // ------------------------------------------------------------------ GED
  ged: program({
    id: 'ged',
    name: 'GED (High School Equivalency)',
    level: 'ged',
    field: 'General Education',
    creditsRequired: 12,
    termsTypical: 1,
    tuitionPerTerm: 150,
    courses: [c('Reasoning Through Language Arts', 'writing'), c('Mathematical Reasoning', 'logic'), c('Science', 'research'), c('Social Studies', 'research')],
    venues: ['community_center', 'library', 'college'],
    prerequisites: 'none',
  }),

  // --------------------------------------------- Community college associate's
  assoc_nursing: program({
    id: 'assoc_nursing',
    name: 'Associate Degree in Nursing (ADN)',
    level: 'associate',
    field: 'Nursing',
    creditsRequired: 72,
    termsTypical: 6,
    tuitionPerTerm: 1800,
    courses: [c('Anatomy & Physiology I', 'medicine'), c('Anatomy & Physiology II', 'medicine'), c('Microbiology', 'research'), c('Nursing Fundamentals', 'medicine'), c('Pharmacology', 'medicine'), c('Med-Surg Nursing', 'medicine'), c('Maternal & Child Health', 'medicine'), c('Psychiatric Nursing', 'medicine'), c('Clinical Practicum', 'medicine'), c('English Composition', 'writing'), c('College Algebra', 'logic'), c('Intro to Psychology', 'research')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  assoc_business: program({
    id: 'assoc_business',
    name: 'Associate of Science in Business',
    level: 'associate',
    field: 'Business',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 1800,
    courses: [c('Intro to Business', 'negotiation'), c('Financial Accounting', 'finance'), c('Managerial Accounting', 'finance'), c('Principles of Marketing', 'charisma'), c('Business Law', 'law'), c('Microeconomics', 'logic'), c('Macroeconomics', 'logic'), c('Business Communication', 'writing'), c('Spreadsheets & Analytics', 'logic'), c('English Composition', 'writing')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  assoc_it: program({
    id: 'assoc_it',
    name: 'Associate of Applied Science in IT',
    level: 'associate',
    field: 'Information Technology',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 1800,
    courses: [c('Intro to Computing', 'programming'), c('Networking Fundamentals', 'logic'), c('Operating Systems', 'programming'), c('Programming I (Python)', 'programming'), c('Programming II', 'programming'), c('Database Basics', 'logic'), c('Cybersecurity Essentials', 'logic'), c('Help Desk Practicum', 'charisma'), c('Technical Writing', 'writing'), c('College Math', 'logic')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  assoc_culinary: program({
    id: 'assoc_culinary',
    name: 'Associate in Culinary Arts',
    level: 'associate',
    field: 'Culinary Arts',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 2400,
    courses: [c('Knife Skills & Fundamentals', 'cooking'), c('Sanitation & Safety', 'cooking'), c('Baking & Pastry I', 'baking'), c('Garde Manger', 'cooking'), c('International Cuisine', 'cooking'), c('Restaurant Operations', 'negotiation'), c('Menu Planning & Costing', 'finance'), c('Beverage Management', 'mixology'), c('Nutrition', 'research'), c('Capstone Kitchen', 'cooking')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  assoc_auto_tech: program({
    id: 'assoc_auto_tech',
    name: 'Associate in Automotive Technology',
    level: 'associate',
    field: 'Automotive Technology',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 2000,
    courses: [c('Engine Repair', 'mechanics'), c('Brakes & Suspension', 'mechanics'), c('Electrical Systems', 'mechanics'), c('Engine Performance', 'mechanics'), c('HVAC Systems', 'handiness'), c('Transmissions', 'mechanics'), c('Hybrid & EV Basics', 'mechanics'), c('Shop Management', 'negotiation'), c('Technical Math', 'logic'), c('ASE Prep', 'mechanics')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  assoc_paralegal: program({
    id: 'assoc_paralegal',
    name: 'Associate in Paralegal Studies',
    level: 'associate',
    field: 'Paralegal Studies',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 1800,
    courses: [c('Intro to Law', 'law'), c('Legal Research & Writing', 'research'), c('Civil Litigation', 'law'), c('Contracts', 'law'), c('Criminal Law & Procedure', 'law'), c('Family Law', 'law'), c('Legal Ethics', 'law'), c('Law Office Technology', 'logic'), c('English Composition', 'writing'), c('Public Speaking', 'charisma')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),

  // ----------------------------------------------------------- Bachelor's
  bs_cs: program({
    id: 'bs_cs',
    name: 'B.S. in Computer Science',
    level: 'bachelor',
    field: 'Computer Science',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Intro to Programming', 'programming'), c('Data Structures', 'programming'), c('Discrete Math', 'logic'), c('Calculus I', 'logic'), c('Calculus II', 'logic'), c('Computer Architecture', 'logic'), c('Algorithms', 'programming'), c('Operating Systems', 'programming'), c('Databases', 'programming'), c('Software Engineering', 'programming'), c('Computer Networks', 'logic'), c('Theory of Computation', 'logic'), c('Machine Learning', 'programming'), c('Senior Capstone', 'programming'), c('Technical Writing', 'writing'), c('Ethics in Computing', 'research')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bsn_nursing: program({
    id: 'bsn_nursing',
    name: 'B.S. in Nursing (BSN)',
    level: 'bachelor',
    field: 'Nursing',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Anatomy & Physiology I', 'medicine'), c('Anatomy & Physiology II', 'medicine'), c('Microbiology', 'research'), c('Chemistry', 'research'), c('Nursing Fundamentals', 'medicine'), c('Pharmacology', 'medicine'), c('Pathophysiology', 'medicine'), c('Med-Surg I', 'medicine'), c('Med-Surg II', 'medicine'), c('Pediatrics', 'medicine'), c('Mental Health Nursing', 'medicine'), c('Community Health', 'medicine'), c('Nursing Research', 'research'), c('Leadership & Management', 'charisma'), c('Clinical Capstone', 'medicine'), c('Statistics', 'logic')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bba_business: program({
    id: 'bba_business',
    name: 'B.B.A. in Business Administration',
    level: 'bachelor',
    field: 'Business Administration',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Intro to Business', 'negotiation'), c('Financial Accounting', 'finance'), c('Managerial Accounting', 'finance'), c('Microeconomics', 'logic'), c('Macroeconomics', 'logic'), c('Marketing', 'charisma'), c('Corporate Finance', 'finance'), c('Operations Management', 'logic'), c('Organizational Behavior', 'charisma'), c('Business Law', 'law'), c('Business Statistics', 'logic'), c('Management Information Systems', 'logic'), c('Strategic Management', 'negotiation'), c('Business Ethics', 'research'), c('Entrepreneurship', 'negotiation'), c('Business Writing', 'writing')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  ba_education: program({
    id: 'ba_education',
    name: 'B.A. in Education',
    level: 'bachelor',
    field: 'Education',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Foundations of Education', 'research'), c('Child Development', 'parenting'), c('Educational Psychology', 'research'), c('Curriculum Design', 'creativity'), c('Classroom Management', 'charisma'), c('Literacy Methods', 'writing'), c('Math Methods', 'logic'), c('Science Methods', 'research'), c('Special Education', 'parenting'), c('Assessment', 'logic'), c('Technology in Education', 'logic'), c('Diversity in Schools', 'research'), c('Student Teaching I', 'charisma'), c('Student Teaching II', 'charisma'), c('Public Speaking', 'charisma'), c('Composition', 'writing')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bs_biology: program({
    id: 'bs_biology',
    name: 'B.S. in Biology',
    level: 'bachelor',
    field: 'Biology',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('General Biology I', 'research'), c('General Biology II', 'research'), c('General Chemistry I', 'research'), c('General Chemistry II', 'research'), c('Organic Chemistry', 'research'), c('Genetics', 'research'), c('Cell Biology', 'research'), c('Ecology', 'research'), c('Physiology', 'medicine'), c('Biochemistry', 'research'), c('Physics I', 'logic'), c('Calculus', 'logic'), c('Biostatistics', 'logic'), c('Research Methods', 'research'), c('Senior Thesis', 'writing'), c('Scientific Writing', 'writing')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  ba_psychology: program({
    id: 'ba_psychology',
    name: 'B.A. in Psychology',
    level: 'bachelor',
    field: 'Psychology',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Intro to Psychology', 'research'), c('Developmental Psychology', 'parenting'), c('Abnormal Psychology', 'research'), c('Social Psychology', 'charisma'), c('Cognitive Psychology', 'logic'), c('Biopsychology', 'medicine'), c('Research Methods', 'research'), c('Statistics for Psychology', 'logic'), c('Personality', 'research'), c('Learning & Memory', 'logic'), c('Counseling Theories', 'charisma'), c('Psychology of Health', 'medicine'), c('Senior Seminar', 'writing'), c('Composition', 'writing'), c('Sociology', 'research'), c('Ethics', 'research')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  ba_english: program({
    id: 'ba_english',
    name: 'B.A. in English',
    level: 'bachelor',
    field: 'English',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Composition I', 'writing'), c('Composition II', 'writing'), c('British Literature', 'research'), c('American Literature', 'research'), c('World Literature', 'research'), c('Creative Writing: Fiction', 'writing'), c('Creative Writing: Poetry', 'creativity'), c('Shakespeare', 'research'), c('Literary Theory', 'logic'), c('Rhetoric', 'charisma'), c('Journalism Basics', 'writing'), c('Editing & Publishing', 'writing'), c('Linguistics', 'research'), c('Film & Literature', 'creativity'), c('Senior Thesis', 'writing'), c('Public Speaking', 'charisma')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bs_engineering: program({
    id: 'bs_engineering',
    name: 'B.S. in Mechanical Engineering',
    level: 'bachelor',
    field: 'Engineering',
    creditsRequired: 128,
    termsTypical: 8,
    tuitionPerTerm: 7200,
    courses: [c('Calculus I', 'logic'), c('Calculus II', 'logic'), c('Differential Equations', 'logic'), c('Physics I', 'logic'), c('Physics II', 'logic'), c('Statics', 'logic'), c('Dynamics', 'logic'), c('Thermodynamics', 'logic'), c('Fluid Mechanics', 'logic'), c('Materials Science', 'research'), c('Machine Design', 'handiness'), c('Manufacturing Processes', 'mechanics'), c('Control Systems', 'programming'), c('CAD', 'creativity'), c('Senior Design I', 'handiness'), c('Senior Design II', 'handiness')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bs_accounting: program({
    id: 'bs_accounting',
    name: 'B.S. in Accounting',
    level: 'bachelor',
    field: 'Accounting',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Financial Accounting', 'finance'), c('Managerial Accounting', 'finance'), c('Intermediate Accounting I', 'finance'), c('Intermediate Accounting II', 'finance'), c('Cost Accounting', 'finance'), c('Federal Taxation', 'finance'), c('Auditing', 'logic'), c('Accounting Information Systems', 'logic'), c('Business Law', 'law'), c('Corporate Finance', 'finance'), c('Economics', 'logic'), c('Statistics', 'logic'), c('Business Ethics', 'research'), c('Advanced Accounting', 'finance'), c('Business Writing', 'writing'), c('Spreadsheet Modeling', 'logic')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  ba_communications: program({
    id: 'ba_communications',
    name: 'B.A. in Communications',
    level: 'bachelor',
    field: 'Communications',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Intro to Communication', 'charisma'), c('Public Speaking', 'charisma'), c('Media Writing', 'writing'), c('Public Relations', 'charisma'), c('Digital Media Production', 'photography'), c('Social Media Strategy', 'creativity'), c('Interpersonal Communication', 'charisma'), c('Persuasion', 'negotiation'), c('Journalism', 'writing'), c('Media Law & Ethics', 'law'), c('Advertising', 'creativity'), c('Communication Research', 'research'), c('Video Production', 'photography'), c('Crisis Communication', 'charisma'), c('Internship', 'charisma'), c('Senior Portfolio', 'creativity')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),
  bs_criminal_justice: program({
    id: 'bs_criminal_justice',
    name: 'B.S. in Criminal Justice',
    level: 'bachelor',
    field: 'Criminal Justice',
    creditsRequired: 120,
    termsTypical: 8,
    tuitionPerTerm: 6500,
    courses: [c('Intro to Criminal Justice', 'law'), c('Criminology', 'research'), c('Criminal Law', 'law'), c('Policing in America', 'law'), c('Corrections', 'law'), c('Courts & Procedure', 'law'), c('Constitutional Law', 'law'), c('Ethics in Justice', 'research'), c('Juvenile Justice', 'parenting'), c('Research Methods', 'research'), c('Statistics', 'logic'), c('Forensic Science Basics', 'research'), c('Victimology', 'research'), c('Crisis Intervention', 'charisma'), c('Internship', 'charisma'), c('Composition', 'writing')],
    venues: ['college'],
    prerequisites: 'high_school',
  }),

  // ------------------------------------------------------------- Master's
  mba: program({
    id: 'mba',
    name: 'Master of Business Administration (MBA)',
    level: 'master',
    field: 'Business Administration',
    creditsRequired: 48,
    termsTypical: 4,
    tuitionPerTerm: 14000,
    courses: [c('Financial Management', 'finance'), c('Marketing Strategy', 'charisma'), c('Operations & Supply Chain', 'logic'), c('Leadership', 'charisma'), c('Managerial Economics', 'logic'), c('Data Analytics for Managers', 'logic'), c('Negotiation', 'negotiation'), c('Corporate Strategy', 'negotiation'), c('Entrepreneurial Finance', 'finance'), c('Business Ethics & Governance', 'law'), c('Global Business', 'research'), c('Capstone Consulting Project', 'negotiation')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),
  msw: program({
    id: 'msw',
    name: 'Master of Social Work (MSW)',
    level: 'master',
    field: 'Social Work',
    creditsRequired: 60,
    termsTypical: 4,
    tuitionPerTerm: 9500,
    courses: [c('Human Behavior & Social Environment', 'research'), c('Social Welfare Policy', 'law'), c('Clinical Practice I', 'charisma'), c('Clinical Practice II', 'charisma'), c('Trauma-Informed Care', 'medicine'), c('Group Work', 'charisma'), c('Research Methods', 'research'), c('Psychopathology', 'medicine'), c('Child & Family Practice', 'parenting'), c('Field Practicum I', 'charisma'), c('Field Practicum II', 'charisma'), c('Ethics', 'research')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),
  med: program({
    id: 'med',
    name: 'Master of Education (M.Ed.)',
    level: 'master',
    field: 'Education',
    creditsRequired: 36,
    termsTypical: 3,
    tuitionPerTerm: 8000,
    courses: [c('Advanced Curriculum Theory', 'creativity'), c('Educational Leadership', 'charisma'), c('Assessment & Data', 'logic'), c('Instructional Technology', 'logic'), c('Equity in Education', 'research'), c('Educational Research', 'research'), c('Literacy Across the Curriculum', 'writing'), c('School Law & Policy', 'law'), c('Capstone Project', 'writing')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),
  ms_cs: program({
    id: 'ms_cs',
    name: 'M.S. in Computer Science',
    level: 'master',
    field: 'Computer Science',
    creditsRequired: 36,
    termsTypical: 3,
    tuitionPerTerm: 11000,
    courses: [c('Advanced Algorithms', 'programming'), c('Distributed Systems', 'programming'), c('Machine Learning', 'programming'), c('Deep Learning', 'programming'), c('Computer Security', 'logic'), c('Compilers', 'programming'), c('Database Systems', 'programming'), c('Research Seminar', 'research'), c("Master's Project", 'programming')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),

  // ----------------------------------------------------------- Professional
  jd: program({
    id: 'jd',
    name: 'Juris Doctor (JD)',
    level: 'professional',
    field: 'Law',
    creditsRequired: 88,
    termsTypical: 6,
    tuitionPerTerm: 24000,
    courses: [c('Civil Procedure', 'law'), c('Contracts', 'law'), c('Torts', 'law'), c('Criminal Law', 'law'), c('Constitutional Law', 'law'), c('Property', 'law'), c('Legal Writing', 'writing'), c('Evidence', 'law'), c('Professional Responsibility', 'law'), c('Business Associations', 'law'), c('Trial Advocacy', 'charisma'), c('Administrative Law', 'law'), c('Legal Clinic', 'negotiation'), c('Bar Prep', 'law')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),
  md: program({
    id: 'md',
    name: 'Doctor of Medicine (MD)',
    level: 'doctorate',
    field: 'Medicine',
    creditsRequired: 160,
    termsTypical: 8,
    tuitionPerTerm: 28000,
    courses: [c('Gross Anatomy', 'medicine'), c('Biochemistry', 'research'), c('Physiology', 'medicine'), c('Histology', 'research'), c('Pathology', 'medicine'), c('Pharmacology', 'medicine'), c('Microbiology & Immunology', 'research'), c('Neuroscience', 'medicine'), c('Clinical Skills', 'medicine'), c('Internal Medicine Clerkship', 'medicine'), c('Surgery Clerkship', 'medicine'), c('Pediatrics Clerkship', 'medicine'), c('OB/GYN Clerkship', 'medicine'), c('Psychiatry Clerkship', 'medicine'), c('Emergency Medicine', 'medicine'), c('Board Prep', 'logic')],
    venues: ['college', 'hospital'],
    prerequisites: 'bachelor',
  }),
  pharmd: program({
    id: 'pharmd',
    name: 'Doctor of Pharmacy (PharmD)',
    level: 'doctorate',
    field: 'Pharmacy',
    creditsRequired: 144,
    termsTypical: 8,
    tuitionPerTerm: 20000,
    courses: [c('Pharmaceutical Chemistry', 'research'), c('Pharmacology I', 'medicine'), c('Pharmacology II', 'medicine'), c('Pharmacokinetics', 'logic'), c('Pharmacotherapy', 'medicine'), c('Compounding Lab', 'medicine'), c('Pharmacy Law', 'law'), c('Patient Counseling', 'charisma'), c('Clinical Rotations I', 'medicine'), c('Clinical Rotations II', 'medicine'), c('Immunizations', 'medicine'), c('Pharmacy Management', 'finance')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),
  dds: program({
    id: 'dds',
    name: 'Doctor of Dental Surgery (DDS)',
    level: 'doctorate',
    field: 'Dentistry',
    creditsRequired: 150,
    termsTypical: 8,
    tuitionPerTerm: 26000,
    courses: [c('Dental Anatomy', 'medicine'), c('Oral Histology', 'research'), c('Operative Dentistry', 'handiness'), c('Periodontics', 'medicine'), c('Prosthodontics', 'handiness'), c('Endodontics', 'medicine'), c('Oral Surgery', 'medicine'), c('Orthodontics', 'medicine'), c('Pediatric Dentistry', 'parenting'), c('Radiology', 'research'), c('Clinical Practice', 'medicine'), c('Practice Management', 'finance')],
    venues: ['college'],
    prerequisites: 'bachelor',
  }),

  // ------------------------------------------------ Certifications / bootcamps
  cert_coding_bootcamp: program({
    id: 'cert_coding_bootcamp',
    name: 'Full-Stack Coding Bootcamp (12 weeks)',
    level: 'some_college',
    field: 'Software Development',
    creditsRequired: 12,
    termsTypical: 1,
    tuitionPerTerm: 12000,
    courses: [c('HTML/CSS/JavaScript', 'programming'), c('React & Front-End', 'programming'), c('Node, APIs & Databases', 'programming'), c('Capstone Project', 'programming')],
    venues: ['college', 'coworking', 'office'],
    prerequisites: 'high_school',
  }),
  cert_cdl: program({
    id: 'cert_cdl',
    name: 'Commercial Driver License (CDL-A) Training',
    level: 'high_school',
    field: 'Commercial Driving',
    creditsRequired: 6,
    termsTypical: 1,
    tuitionPerTerm: 4500,
    courses: [c('CDL Classroom & Permit', 'driving'), c('Range Driving & Backing', 'driving'), c('Road Driving & Skills Test', 'driving')],
    venues: ['college', 'warehouse'],
    prerequisites: 'high_school',
  }),
  cert_emt: program({
    id: 'cert_emt',
    name: 'EMT-Basic Certification',
    level: 'some_college',
    field: 'Emergency Medical Services',
    creditsRequired: 8,
    termsTypical: 1,
    tuitionPerTerm: 1400,
    courses: [c('Patient Assessment', 'medicine'), c('Airway & CPR', 'medicine'), c('Trauma Care', 'medicine'), c('Ambulance Ride-Alongs', 'driving')],
    venues: ['college', 'fire_station', 'hospital'],
    prerequisites: 'high_school',
  }),
  cert_cna: program({
    id: 'cert_cna',
    name: 'Certified Nursing Assistant (CNA)',
    level: 'high_school',
    field: 'Nursing Assistant',
    creditsRequired: 6,
    termsTypical: 1,
    tuitionPerTerm: 1200,
    courses: [c('Basic Patient Care', 'medicine'), c('Infection Control & Safety', 'medicine'), c('Clinical Hours', 'medicine')],
    venues: ['college', 'hospital', 'community_center'],
    prerequisites: 'high_school',
  }),
  cert_real_estate: program({
    id: 'cert_real_estate',
    name: 'Real Estate Salesperson License Course',
    level: 'high_school',
    field: 'Real Estate',
    creditsRequired: 6,
    termsTypical: 1,
    tuitionPerTerm: 600,
    courses: [c('Principles of Real Estate', 'negotiation'), c('Real Estate Law & Contracts', 'law'), c('Finance & Exam Prep', 'finance')],
    venues: ['college', 'real_estate', 'community_center'],
    prerequisites: 'high_school',
  }),
  cert_cosmetology: program({
    id: 'cert_cosmetology',
    name: 'Cosmetology License Program',
    level: 'some_college',
    field: 'Cosmetology',
    creditsRequired: 30,
    termsTypical: 3,
    tuitionPerTerm: 5500,
    courses: [c('Hair Cutting', 'handiness'), c('Color & Chemical Services', 'handiness'), c('Skin & Nails', 'handiness'), c('Salon Business', 'negotiation'), c('State Board Prep', 'logic'), c('Client Consultation', 'charisma')],
    venues: ['college', 'salon'],
    prerequisites: 'high_school',
  }),
  cert_personal_trainer: program({
    id: 'cert_personal_trainer',
    name: 'Certified Personal Trainer (NASM/ACE)',
    level: 'high_school',
    field: 'Fitness',
    creditsRequired: 6,
    termsTypical: 1,
    tuitionPerTerm: 900,
    courses: [c('Exercise Science', 'fitness'), c('Program Design', 'fitness'), c('Client Assessment & Coaching', 'charisma')],
    venues: ['gym', 'college', 'community_center'],
    prerequisites: 'high_school',
  }),
  cert_cpa_prep: program({
    id: 'cert_cpa_prep',
    name: 'CPA Exam Review',
    level: 'bachelor',
    field: 'Accounting',
    creditsRequired: 12,
    termsTypical: 1,
    tuitionPerTerm: 2500,
    courses: [c('Auditing & Attestation', 'finance'), c('Financial Accounting & Reporting', 'finance'), c('Regulation', 'law'), c('Business Analysis', 'logic')],
    venues: ['college', 'accountant', 'library'],
    prerequisites: 'bachelor',
  }),
  cert_pharmacy_tech: program({
    id: 'cert_pharmacy_tech',
    name: 'Pharmacy Technician Certificate',
    level: 'some_college',
    field: 'Pharmacy',
    creditsRequired: 8,
    termsTypical: 1,
    tuitionPerTerm: 1800,
    courses: [c('Pharmacy Calculations', 'logic'), c('Drug Classifications', 'medicine'), c('Pharmacy Law & Practice', 'law'), c('Externship', 'medicine')],
    venues: ['college', 'pharmacy'],
    prerequisites: 'high_school',
  }),
  cert_teaching_license: program({
    id: 'cert_teaching_license',
    name: 'Alternative Teacher Certification',
    level: 'bachelor',
    field: 'Education',
    creditsRequired: 12,
    termsTypical: 2,
    tuitionPerTerm: 2200,
    courses: [c('Classroom Management', 'charisma'), c('Pedagogy & Assessment', 'logic'), c('Content Exam Prep', 'research'), c('Supervised Teaching', 'charisma')],
    venues: ['college', 'school'],
    prerequisites: 'bachelor',
  }),
};

export const PROGRAM_IDS = Object.keys(PROGRAMS);

/** Ordering of education levels for prerequisite checks. */
export const EDUCATION_LEVEL_ORDER = ['none', 'elementary', 'middle', 'high_school', 'ged', 'some_college', 'associate', 'bachelor', 'master', 'professional', 'doctorate'] as const;
