/**
 * Skill catalog. Level 1 needs 100 xp; each further level needs ~1.35× the previous.
 * `xpCurve[i]` is the xp required to go from level i to level i+1 (consumed by core/effects.ts addSkillXp).
 */
import type { SkillDef } from './types';

export const SKILL_XP_CURVE: number[] = (() => {
  const out: number[] = [];
  let v = 100;
  for (let i = 0; i < 10; i++) {
    out.push(Math.round(v));
    v *= 1.35;
  }
  return out;
})();

/** Total xp needed to reach a level from 0. */
export function xpToLevel(level: number): number {
  let t = 0;
  for (let i = 0; i < Math.min(10, level); i++) t += SKILL_XP_CURVE[i];
  return t;
}

function skill(id: string, name: string, category: SkillDef['category'], icon: string, description: string, unlocks: Record<number, string>): SkillDef {
  return { id, name, category, icon, description, xpCurve: [...SKILL_XP_CURVE], unlocks };
}

export const SKILLS: Record<string, SkillDef> = {
  cooking: skill('cooking', 'Cooking', 'practical', 'chef-hat', 'Turning groceries into meals that are worth eating. Higher levels waste less, burn less, and impress more.', {
    1: 'Basic meals no longer come out burnt.',
    2: 'Meal prep: cook double portions as leftovers.',
    3: 'Better recipes: stir-fries, pasta dishes, roasts.',
    4: 'Meals restore more hunger and give a small fun bonus.',
    5: 'Cook for guests — dinner parties boost friendships.',
    6: 'Gourmet recipes unlocked.',
    7: 'Ingredient efficiency: recipes use 20% less.',
    8: 'Signature dish — a rare "Delighted" moodlet for everyone who eats it.',
    9: 'Eligible for chef-track career promotions.',
    10: 'Master chef: every meal is gourmet quality.',
  }),
  baking: skill('baking', 'Baking', 'practical', 'cake', 'Bread, pastries, and cakes. Precise, patient, and a great gift for neighbors.', {
    1: 'Cookies and quick breads.',
    2: 'Baked goods can be gifted for a friendship boost.',
    3: 'Cakes and pies.',
    4: 'Bake for birthdays and holidays.',
    5: 'Sourdough and laminated dough.',
    6: 'Sell baked goods at the farmers market.',
    7: 'Wedding cakes on commission.',
    8: 'Baked goods give a "Comforted" moodlet.',
    9: 'Bakery career fast-track.',
    10: 'Master baker.',
  }),
  mixology: skill('mixology', 'Mixology', 'practical', 'cocktail', 'Cocktails, pours, and knowing when to cut someone off.', {
    1: 'Pour a decent drink at home.',
    2: 'Classic cocktails.',
    3: 'Bartending jobs available.',
    4: 'Guests at your parties have more fun.',
    5: 'Craft cocktails; better tips as a bartender.',
    6: 'Flair bartending — a show at the bar.',
    7: 'Invent a signature cocktail.',
    8: 'Bar manager track.',
    9: 'Judge cocktail competitions.',
    10: 'Legendary bartender.',
  }),
  fitness: skill('fitness', 'Fitness', 'physical', 'dumbbell', 'Strength and conditioning. Workouts get more effective and less exhausting.', {
    1: 'Workouts drain less energy.',
    2: 'Fitness gains from exercise +25%.',
    3: 'Hygiene loss from workouts reduced.',
    4: 'Personal trainer jobs.',
    5: 'Weight management is easier; higher TDEE.',
    6: 'Lift heavy: strength-based outcomes improve.',
    7: 'Recover faster from injuries.',
    8: 'Illness resistance bonus.',
    9: 'Compete in local competitions.',
    10: 'Peak physical condition.',
  }),
  athletics: skill('athletics', 'Athletics', 'physical', 'run', 'Running, team sports, and endurance.', {
    1: 'Jog without getting winded.',
    2: 'Join pickup games at the park.',
    3: 'Run a 5K.',
    4: 'Bike commuting is faster and cheaper.',
    5: 'Rec league team sports.',
    6: 'Half marathon.',
    7: 'Coach youth sports (volunteer).',
    8: 'Marathon.',
    9: 'Semi-pro opportunities.',
    10: 'Elite athlete.',
  }),
  charisma: skill('charisma', 'Charisma', 'social', 'sparkles', 'Reading a room, small talk, persuasion, and presence.', {
    1: 'Small talk with strangers goes smoothly.',
    2: 'Better first impressions.',
    3: 'Interviews and dates go better.',
    4: 'Ask for favors.',
    5: 'Give a rousing toast at gatherings.',
    6: 'Sales and management promotions easier.',
    7: 'Defuse arguments.',
    8: 'Public speaking events.',
    9: 'Run for local office.',
    10: 'Magnetic presence.',
  }),
  comedy: skill('comedy', 'Comedy', 'social', 'laugh', 'Timing, jokes, and knowing your audience.', {
    1: 'Jokes land more often than not.',
    2: 'Cheer up a friend.',
    3: 'Open mic night at the bar.',
    4: 'Roast without hurting feelings.',
    5: 'Paid comedy gigs.',
    6: 'Crowd work.',
    7: 'Write a tight ten.',
    8: 'Headline a local show.',
    9: 'Comedy special.',
    10: 'Legend of the scene.',
  }),
  negotiation: skill('negotiation', 'Negotiation', 'social', 'handshake', 'Getting a better deal — salary, rent, a used car, or a fine.', {
    1: 'Haggle at the flea market.',
    2: 'Negotiate salary at hiring (+5%).',
    3: 'Talk down a repair bill.',
    4: 'Negotiate rent.',
    5: 'Contest tickets successfully more often.',
    6: 'Better used-car prices.',
    7: 'Salary negotiations +15%.',
    8: 'Business deals.',
    9: 'Settle lawsuits favorably.',
    10: 'Master negotiator.',
  }),
  logic: skill('logic', 'Logic', 'mental', 'brain', 'Puzzles, math, chess, and structured thinking.', {
    1: 'Sudoku and crosswords for fun.',
    2: 'Homework and studying go faster.',
    3: 'Chess at the park.',
    4: 'Better exam scores.',
    5: 'Analyst careers.',
    6: 'Win at chess more often.',
    7: 'Taxes done right, every time.',
    8: 'Research gains faster.',
    9: 'Scientist track.',
    10: 'Brilliant mind.',
  }),
  research: skill('research', 'Research', 'mental', 'book-open', 'Finding things out: libraries, databases, and asking the right questions.', {
    1: 'Look things up effectively.',
    2: 'Better grades in college courses.',
    3: 'Check symptoms online more accurately.',
    4: 'Find better deals and jobs.',
    5: 'Lab tech / journalist careers.',
    6: 'Grant writing.',
    7: 'Publish articles.',
    8: 'Academic promotions.',
    9: 'Lead research projects.',
    10: 'Renowned researcher.',
  }),
  programming: skill('programming', 'Programming', 'professional', 'code', 'Writing software. Pays well if you can stand the meetings.', {
    1: 'Fix your own laptop.',
    2: 'Simple scripts and websites.',
    3: 'Freelance gigs online.',
    4: 'Junior developer jobs.',
    5: 'Build an app on the side.',
    6: 'Senior developer promotions.',
    7: 'Side project income.',
    8: 'Tech lead.',
    9: 'Start a startup.',
    10: 'Rockstar engineer.',
  }),
  creativity: skill('creativity', 'Creativity', 'creative', 'lightbulb', 'General creative thinking that feeds every art and craft.', {
    1: 'Inspired moodlets last longer.',
    2: 'Boost to painting, writing, music xp.',
    3: 'Design gigs.',
    4: 'Decorate your home for a comfort bonus.',
    5: 'Marketing/design careers.',
    6: 'Original ideas in freeform actions succeed more.',
    7: 'Creative director track.',
    8: 'Gallery shows.',
    9: 'Creative grants.',
    10: 'Visionary.',
  }),
  writing: skill('writing', 'Writing', 'creative', 'pen', 'Journals, short stories, novels, articles, and the odd angry email.', {
    1: 'Journaling relieves stress.',
    2: 'Short stories.',
    3: 'Freelance writing gigs.',
    4: 'Blog with a following.',
    5: 'Write a novel (sell for royalties).',
    6: 'Journalist career.',
    7: 'Better cover letters (interviews +).',
    8: 'Bestseller potential.',
    9: 'Screenwriting.',
    10: 'Celebrated author.',
  }),
  painting: skill('painting', 'Painting', 'creative', 'palette', 'Canvas, watercolor, sketching.', {
    1: 'Sketches worth keeping.',
    2: 'Sell small pieces online.',
    3: 'Paintings improve home decor.',
    4: 'Commissioned portraits.',
    5: 'Gallery submissions.',
    6: 'Murals.',
    7: 'Teach classes at the art studio.',
    8: 'Museum interest.',
    9: 'Masterpieces sell high.',
    10: 'Master painter.',
  }),
  photography: skill('photography', 'Photography', 'creative', 'camera', 'Composition, light, and knowing when to press the shutter.', {
    1: 'Nice phone photos; social posts get more likes.',
    2: 'Sell stock photos.',
    3: 'Event photography gigs.',
    4: 'Wedding photography.',
    5: 'Photographer career.',
    6: 'Portrait studio.',
    7: 'Photojournalism.',
    8: 'Exhibitions.',
    9: 'Famous shots.',
    10: 'Master photographer.',
  }),
  music: skill('music', 'Music', 'creative', 'music', 'Theory, rhythm, and ear. Feeds instruments and singing.', {
    1: 'Keep time; learn songs faster.',
    2: 'Jam with friends.',
    3: 'Write a song.',
    4: 'Busking income.',
    5: 'Join a band.',
    6: 'Record an album.',
    7: 'Paid gigs at bars.',
    8: 'Producer work.',
    9: 'Tours.',
    10: 'Music legend.',
  }),
  singing: skill('singing', 'Singing', 'creative', 'mic', 'From shower singing to karaoke to the stage.', {
    1: 'Karaoke without shame.',
    2: 'Sing a lullaby (kids sleep better).',
    3: 'Church choir / open mic.',
    4: 'Win karaoke nights.',
    5: 'Wedding singer gigs.',
    6: 'Serenade (romance boost).',
    7: 'Lead vocalist.',
    8: 'Studio recordings.',
    9: 'Regional fame.',
    10: 'Star vocalist.',
  }),
  dancing: skill('dancing', 'Dancing', 'physical', 'dance', 'Club dancing, partner dancing, and not embarrassing yourself at weddings.', {
    1: 'Dance at the club without a "Embarrassed" moodlet.',
    2: 'Partner dance basics.',
    3: 'Dance classes teach faster.',
    4: 'Impress dates.',
    5: 'Dance instructor gigs.',
    6: 'Competitions.',
    7: 'Choreography.',
    8: 'Performances.',
    9: 'Professional dancer.',
    10: 'Show stopper.',
  }),
  guitar: skill('guitar', 'Guitar', 'creative', 'guitar', 'Acoustic or electric. Calloused fingers included.', {
    1: 'Four chords and the truth.',
    2: 'Play for friends.',
    3: 'Busk for tips.',
    4: 'Write songs.',
    5: 'Band-ready.',
    6: 'Solos.',
    7: 'Paid gigs.',
    8: 'Session musician.',
    9: 'Recording artist.',
    10: 'Guitar hero.',
  }),
  piano: skill('piano', 'Piano', 'creative', 'piano', 'Keys — from scales to Chopin to lounge standards.', {
    1: 'Simple melodies.',
    2: 'Play for family.',
    3: 'Accompany singers.',
    4: 'Teach kids piano (side income).',
    5: 'Restaurant/hotel gigs.',
    6: 'Compose.',
    7: 'Recitals.',
    8: 'Concert pieces.',
    9: 'Touring pianist.',
    10: 'Virtuoso.',
  }),
  gardening: skill('gardening', 'Gardening', 'practical', 'sprout', 'Growing food and flowers. Saves on groceries and soothes the mind.', {
    1: 'Houseplants survive.',
    2: 'Herbs and tomatoes.',
    3: 'Vegetable beds cut the grocery bill.',
    4: 'Flowers for gifts.',
    5: 'Sell produce at the farmers market.',
    6: 'Landscaper career track.',
    7: 'Fruit trees.',
    8: 'Rare plants.',
    9: 'Community garden leadership.',
    10: 'Green thumb legend.',
  }),
  handiness: skill('handiness', 'Handiness', 'practical', 'wrench', 'Fixing what breaks and building what you need.', {
    1: 'Repair small appliances.',
    2: 'Assemble furniture fast.',
    3: 'Fix plumbing and electrical basics.',
    4: 'Upgrade objects.',
    5: 'Electrician/plumber careers.',
    6: 'Build furniture.',
    7: 'Home renovations raise property value.',
    8: 'Contractor gigs.',
    9: 'Master craftsman.',
    10: 'Can fix anything.',
  }),
  mechanics: skill('mechanics', 'Mechanics', 'practical', 'car', 'Cars, bikes, and engines.', {
    1: 'Change your own oil.',
    2: 'Fix a flat.',
    3: 'Diagnose issues before the shop does.',
    4: 'Repair your own car (save money).',
    5: 'Mechanic career.',
    6: 'Restore vehicles for profit.',
    7: 'Performance tuning.',
    8: 'Own a shop.',
    9: 'Race team.',
    10: 'Master mechanic.',
  }),
  driving: skill('driving', 'Driving', 'practical', 'steering-wheel', 'Safe, confident driving. Fewer accidents, fewer tickets.', {
    1: 'Pass the road test.',
    2: 'Fewer accidents.',
    3: 'Rideshare/delivery driver ratings up.',
    4: 'Better fuel economy.',
    5: 'Highway confidence; faster trips.',
    6: 'Truck driving (CDL).',
    7: 'Defensive driving; insurance discount.',
    8: 'Bus driver.',
    9: 'Stunt driving gigs.',
    10: 'Professional driver.',
  }),
  gaming: skill('gaming', 'Gaming', 'mental', 'gamepad', 'Video games, competitive and casual.', {
    1: 'Games are more fun.',
    2: 'Online friends.',
    3: 'Ranked play.',
    4: 'Streaming viewers.',
    5: 'Tournament winnings.',
    6: 'Sponsorships.',
    7: 'Esports team.',
    8: 'Pro gamer.',
    9: 'Championship.',
    10: 'Legend.',
  }),
  parenting: skill('parenting', 'Parenting', 'social', 'baby', 'Raising kids without losing your mind.', {
    1: 'Diaper changes go faster.',
    2: 'Calm a crying baby.',
    3: 'Help with homework effectively.',
    4: 'Kids have better moods.',
    5: 'Handle teen drama.',
    6: 'Teacher/daycare careers.',
    7: 'Kids gain skills faster.',
    8: 'Family bonds strengthen.',
    9: 'Foster/adoption approval.',
    10: 'Parent of the year.',
  }),
  medicine: skill('medicine', 'Medicine', 'professional', 'stethoscope', 'First aid through clinical medicine.', {
    1: 'First aid at home works better.',
    2: 'Recognize symptoms early.',
    3: 'CNA/EMT careers.',
    4: 'Treat minor injuries at home.',
    5: 'Nursing track.',
    6: 'Diagnose family members.',
    7: 'Physician track.',
    8: 'Surgery.',
    9: 'Specialist.',
    10: 'Renowned doctor.',
  }),
  law: skill('law', 'Law', 'professional', 'scale', 'Knowing your rights and how the system works.', {
    1: 'Contest tickets.',
    2: 'Read a lease properly.',
    3: 'Paralegal jobs.',
    4: 'Represent yourself in small claims.',
    5: 'Negotiate plea deals.',
    6: 'Lawyer career.',
    7: 'Win civil suits.',
    8: 'Criminal defense.',
    9: 'Partner track.',
    10: 'Legal titan.',
  }),
  finance: skill('finance', 'Finance', 'professional', 'chart', 'Budgets, investing, taxes, and not getting fleeced.', {
    1: 'Track a budget.',
    2: 'Avoid overdraft fees.',
    3: 'Do your own taxes.',
    4: 'Better loan rates.',
    5: 'Invest with better returns.',
    6: 'Financial analyst career.',
    7: 'Tax optimization.',
    8: 'Advise others.',
    9: 'Fund manager.',
    10: 'Money wizard.',
  }),
  crafting: skill('crafting', 'Crafting', 'creative', 'scissors', 'Knitting, woodworking, sewing, and making things by hand.', {
    1: 'Mend clothes.',
    2: 'Simple crafts to gift.',
    3: 'Sell crafts online.',
    4: 'Furniture from scratch.',
    5: 'Craft fair booth.',
    6: 'Custom commissions.',
    7: 'Teach workshops.',
    8: 'Etsy empire.',
    9: 'Artisan renown.',
    10: 'Master craftsperson.',
  }),
  fishing: skill('fishing', 'Fishing', 'practical', 'fish', 'Patience, tackle, and a good spot.', {
    1: 'Catch something occasionally.',
    2: 'Fresh fish for dinner.',
    3: 'Better catch rates.',
    4: 'Sell fish at the market.',
    5: 'Fishing trips with friends.',
    6: 'Trophy fish.',
    7: 'Fly fishing.',
    8: 'Charter guide income.',
    9: 'Tournaments.',
    10: 'Legendary angler.',
  }),
  spanish: skill('spanish', 'Spanish', 'mental', 'globe', 'Speaking Spanish — useful across most of the country.', {
    1: 'Order food and say hello.',
    2: 'Basic conversations.',
    3: 'Befriend Spanish-speaking neighbors more easily.',
    4: 'Bilingual job bonus.',
    5: 'Fluent conversations.',
    6: 'Translate for others.',
    7: 'Interpreter gigs.',
    8: 'Teach Spanish.',
    9: 'Literary Spanish.',
    10: 'Native-level fluency.',
  }),
};

export const SKILL_IDS = Object.keys(SKILLS);
