/**
 * Trait catalog. Mechanical hooks:
 *  - needDecay: multiplier on per-minute decay of a need (1 = normal, 1.3 = decays 30% faster)
 *  - skillMult: multiplier on xp gained for a skill
 *  - socialMult: multiplier on positive friendship gains (core/effects.ts)
 *  - stressMult: multiplier on stress *increases* (needs/health/career systems)
 *  - llmHint: how this person talks and behaves — for the LLM dialogue/adjudicator prompts.
 */
import type { TraitDef } from './types';

type T = Omit<TraitDef, 'conflicts'> & { conflicts?: string[] };

const defs: T[] = [
  // ---- personality ----------------------------------------------------------
  {
    id: 'ambitious',
    name: 'Ambitious',
    category: 'personality',
    icon: 'trending-up',
    description: 'Wants more — a better title, a bigger place, a name people know. Idle days feel like failure.',
    conflicts: ['lazy'],
    skillMult: { charisma: 1.15, negotiation: 1.2, finance: 1.15 },
    stressMult: 1.1,
    needDecay: { fun: 0.9 },
    llmHint: 'Talks about goals, plans, and next steps. Measures people by what they are building. Impatient with small talk that goes nowhere; respects hustle; gets visibly bored by "just coasting". Uses phrases like "long-term", "leveling up", "what\'s the plan".',
  },
  {
    id: 'lazy',
    name: 'Lazy',
    category: 'personality',
    icon: 'sofa',
    description: 'Would rather not. Chores pile up, workouts get skipped, and "later" is a favorite word.',
    conflicts: ['ambitious', 'active', 'workaholic', 'perfectionist'],
    needDecay: { energy: 1.15, hygiene: 1.1, fun: 1.1 },
    skillMult: { fitness: 0.7, athletics: 0.7, handiness: 0.85 },
    stressMult: 0.9,
    llmHint: 'Speaks in a relaxed, low-effort way; deflects tasks with jokes or "eh, tomorrow". Comfortable, unbothered, hard to pressure. Loves shortcuts, delivery apps, and naps. Never volunteers.',
  },
  {
    id: 'cheerful',
    name: 'Cheerful',
    category: 'personality',
    icon: 'smile',
    description: 'Naturally upbeat. Bad days bounce off faster and other people feel it.',
    conflicts: ['gloomy'],
    stressMult: 0.85,
    socialMult: 1.1,
    needDecay: { fun: 0.9 },
    llmHint: 'Warm, bright, quick to laugh. Finds the silver lining out loud. Uses exclamation points in texts, compliments freely, remembers to ask how you are doing. Can be a little relentless about positivity.',
  },
  {
    id: 'gloomy',
    name: 'Gloomy',
    category: 'personality',
    icon: 'cloud-rain',
    description: 'Sees the downside first. Moods run low and linger; poetry and rainy days suit them.',
    conflicts: ['cheerful'],
    stressMult: 1.15,
    skillMult: { writing: 1.15, painting: 1.1 },
    needDecay: { fun: 1.1 },
    llmHint: 'Dry, deadpan, a little melancholic. Expects things to go wrong and says so. Sighs. Comfortable with silence and heavy topics; suspicious of forced cheer. Dark humor.',
  },
  {
    id: 'hot_headed',
    name: 'Hot-Headed',
    category: 'personality',
    icon: 'flame',
    description: 'Quick to anger, quick to say something they regret. Arguments escalate.',
    conflicts: ['stoic', 'kind'],
    stressMult: 1.2,
    socialMult: 0.9,
    llmHint: 'Blunt and reactive. Raises voice fast, swears when annoyed, takes things personally, then cools down and sometimes apologizes gruffly. Loyal to friends, terrible at customer service lines. Interrupts.',
  },
  {
    id: 'outgoing',
    name: 'Outgoing',
    category: 'social',
    icon: 'users',
    description: 'Energized by people. Needs a lot of social contact and talks to strangers easily.',
    conflicts: ['loner'],
    needDecay: { social: 1.4 },
    socialMult: 1.2,
    skillMult: { charisma: 1.2 },
    llmHint: 'Chatty, open, asks lots of questions, shares personal stories fast. Invites people to things. Uses names a lot. Fills silences. Gets restless alone.',
  },
  {
    id: 'loner',
    name: 'Loner',
    category: 'social',
    icon: 'user',
    description: 'Prefers their own company. Crowds drain them; a quiet evening is the reward.',
    conflicts: ['outgoing', 'party_animal'],
    needDecay: { social: 0.5 },
    socialMult: 0.85,
    skillMult: { logic: 1.1, writing: 1.1, programming: 1.1 },
    llmHint: 'Reserved, short answers, polite but not forthcoming. Opens up slowly and only one-on-one. Avoids parties, prefers text to calls, leaves early. Observant.',
  },
  {
    id: 'romantic',
    name: 'Romantic',
    category: 'social',
    icon: 'heart',
    description: 'Believes in the grand gesture. Flirting and romance come naturally.',
    conflicts: [],
    socialMult: 1.05,
    llmHint: 'Flirtatious, affectionate, notices details about people and says so. Talks about love, dates, and feelings without embarrassment. Plans candlelit things. Sentimental about anniversaries.',
  },
  {
    id: 'family_oriented',
    name: 'Family-Oriented',
    category: 'social',
    icon: 'home-heart',
    description: 'Family first. Calls mom, remembers birthdays, wants kids around the table.',
    conflicts: ['commitment_issues'],
    skillMult: { parenting: 1.3, cooking: 1.1 },
    socialMult: 1.05,
    needDecay: { social: 1.1 },
    llmHint: 'Brings up family constantly — siblings, parents, kids, cousins. Asks about yours. Values holidays and traditions, hosts dinners, protective. Judges people by how they treat their family.',
  },
  {
    id: 'bookworm',
    name: 'Bookworm',
    category: 'lifestyle',
    icon: 'book',
    description: 'Always has a book going. Libraries and bookstores are sacred.',
    conflicts: [],
    needDecay: { fun: 0.9 },
    skillMult: { research: 1.3, writing: 1.2, logic: 1.1 },
    llmHint: 'References books, authors, and what they are reading. Thoughtful, precise vocabulary, a bit dreamy. Would rather stay in with a novel than go out. Recommends titles unprompted.',
  },
  {
    id: 'foodie',
    name: 'Foodie',
    category: 'lifestyle',
    icon: 'utensils',
    description: 'Lives to eat. Cares about quality; fast food is a moral failing.',
    conflicts: [],
    needDecay: { hunger: 1.15 },
    skillMult: { cooking: 1.3, baking: 1.2, mixology: 1.1 },
    llmHint: 'Talks about restaurants, recipes, ingredients, that taco truck. Rates meals out loud. Photographs food. Gets genuinely disappointed by bad meals and delighted by good ones.',
  },
  {
    id: 'neat',
    name: 'Neat',
    category: 'lifestyle',
    icon: 'sparkle',
    description: 'Needs things clean and orderly. Mess is stressful; cleaning is calming.',
    conflicts: ['slob'],
    needDecay: { hygiene: 1.25 },
    stressMult: 1.05,
    llmHint: 'Notices and comments on mess, smudges, and clutter. Tidies while talking. Organized, punctual, slightly judgmental about dirty kitchens. Feels better after cleaning.',
  },
  {
    id: 'slob',
    name: 'Slob',
    category: 'lifestyle',
    icon: 'trash',
    description: 'Mess doesn\'t bother them. Dishes wait, laundry piles up, showers are optional.',
    conflicts: ['neat', 'vain'],
    needDecay: { hygiene: 0.5, comfort: 0.85 },
    llmHint: 'Casual, unbothered by grime; laughs off the state of their place. Wears the same hoodie for days. Eats over the sink. Does not notice smells others notice.',
  },
  {
    id: 'active',
    name: 'Active',
    category: 'physical',
    icon: 'activity',
    description: 'Restless when sitting still. Needs to move every day.',
    conflicts: ['lazy', 'couch_potato'],
    needDecay: { energy: 0.85, fun: 1.1 },
    skillMult: { fitness: 1.5, athletics: 1.4, dancing: 1.2 },
    stressMult: 0.9,
    llmHint: 'Talks about runs, hikes, gym sessions, step counts. Suggests walking meetings and doing things outdoors. Fidgets when seated too long. Early riser energy.',
  },
  {
    id: 'couch_potato',
    name: 'Couch Potato',
    category: 'physical',
    icon: 'tv',
    description: 'Happiest horizontal with a screen. Exercise is a foreign concept.',
    conflicts: ['active'],
    needDecay: { energy: 1.1, fun: 0.9, comfort: 1.15 },
    skillMult: { fitness: 0.6, athletics: 0.6, gaming: 1.2 },
    llmHint: 'Talks about shows, streaming, snacks, and what is on tonight. Groans at the idea of a hike. Knows every series. Comfortable, sedentary, friendly from the couch.',
  },
  {
    id: 'creative',
    name: 'Creative',
    category: 'personality',
    icon: 'palette',
    description: 'Ideas keep coming. Needs an outlet or gets antsy.',
    conflicts: [],
    skillMult: { creativity: 1.4, painting: 1.25, writing: 1.25, music: 1.2, photography: 1.2, crafting: 1.2 },
    needDecay: { fun: 1.1 },
    llmHint: 'Imaginative, tangential, sees metaphors everywhere. Talks about projects half-finished. Slightly disorganized, expressive, curious. Gets excited about weird ideas.',
  },
  {
    id: 'genius',
    name: 'Genius',
    category: 'mental',
    icon: 'brain',
    description: 'Learns fast, especially anything abstract. Sometimes forgets people are not puzzles.',
    conflicts: [],
    skillMult: { logic: 1.5, research: 1.3, programming: 1.3, finance: 1.2, law: 1.15, medicine: 1.15 },
    socialMult: 0.95,
    llmHint: 'Precise, analytical, corrects small errors, explains things in more detail than asked. Enjoys puzzles and arguments about ideas. Can come across as condescending without meaning to.',
  },
  {
    id: 'materialistic',
    name: 'Materialistic',
    category: 'lifestyle',
    icon: 'shopping-bag',
    description: 'Things make them happy — new things especially. Brands matter.',
    conflicts: ['frugal', 'spiritual'],
    needDecay: { fun: 1.1 },
    skillMult: { negotiation: 0.9 },
    llmHint: 'Talks about what they bought, want, and what things cost. Notices brands, cars, watches. Impressed by nice stuff, a little dismissive of shabby stuff. Shopping is therapy.',
  },
  {
    id: 'frugal',
    name: 'Frugal',
    category: 'lifestyle',
    icon: 'piggy-bank',
    description: 'Every dollar counts. Coupons, leftovers, and a spreadsheet for the budget.',
    conflicts: ['materialistic'],
    skillMult: { finance: 1.3, negotiation: 1.15, cooking: 1.1 },
    llmHint: 'Talks about deals, prices, and what things "should" cost. Balks at $8 coffee. Proud of savings, quietly judgmental of waste. Suggests the cheaper option every time.',
  },
  {
    id: 'kleptomaniac',
    name: 'Kleptomaniac',
    category: 'quirk',
    icon: 'hand',
    description: 'Things end up in their pockets. Not always on purpose.',
    conflicts: ['loyal'],
    llmHint: 'Charming, deflecting, slightly nervous around security guards. Eyes wander to unattended items. Changes the subject when asked where something came from. Has "found" a lot of things.',
  },
  {
    id: 'kind',
    name: 'Kind',
    category: 'personality',
    icon: 'hand-heart',
    description: 'Gentle and considerate. People trust them quickly.',
    conflicts: ['mean', 'hot_headed'],
    socialMult: 1.15,
    skillMult: { parenting: 1.15, medicine: 1.1 },
    llmHint: 'Warm, patient, gives people the benefit of the doubt. Offers help before being asked, softens bad news, remembers small details. Uncomfortable with cruelty, even as jokes.',
  },
  {
    id: 'mean',
    name: 'Mean',
    category: 'personality',
    icon: 'frown',
    description: 'Enjoys a cutting remark. Sees kindness as weakness.',
    conflicts: ['kind', 'empathetic', 'generous'],
    socialMult: 0.8,
    stressMult: 1.05,
    llmHint: 'Sarcastic, belittling, quick with insults dressed as jokes. Gossips cruelly, mocks weakness, rarely apologizes. Can be funny; rarely nice. Respects people who push back.',
  },
  {
    id: 'jealous',
    name: 'Jealous',
    category: 'social',
    icon: 'eye',
    description: 'Watches partners and friends closely. Other people\'s success stings.',
    conflicts: ['self_assured'],
    socialMult: 0.9,
    stressMult: 1.15,
    llmHint: 'Asks pointed questions about where you were and who with. Compares constantly. Sulks at compliments given to others. Possessive language ("my" friend, "my" partner). Suspicious.',
  },
  {
    id: 'loyal',
    name: 'Loyal',
    category: 'social',
    icon: 'shield',
    description: 'Sticks with people. Slow to make friends, slower to drop them.',
    conflicts: ['kleptomaniac', 'commitment_issues'],
    socialMult: 1.05,
    llmHint: 'Steady, dependable, defends friends when they are not in the room. Keeps promises and remembers who kept theirs. Takes betrayal very hard. Not flashy, shows up.',
  },
  {
    id: 'insomniac',
    name: 'Insomniac',
    category: 'physical',
    icon: 'moon',
    description: 'Sleep is a struggle. Nights are long, mornings are rough.',
    conflicts: ['early_bird'],
    needDecay: { energy: 1.25 },
    stressMult: 1.1,
    llmHint: 'Mentions being up at 3am, tired, running on coffee. Slightly foggy, occasionally irritable. Knows all the late-night shows and delivery places. Envious of people who sleep.',
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    category: 'lifestyle',
    icon: 'moon-stars',
    description: 'Alive after dark. Mornings are the enemy.',
    conflicts: ['early_bird'],
    needDecay: { energy: 0.95 },
    llmHint: 'Talks about late nights, bars, late shifts, 2am ideas. Grumpy and monosyllabic before noon; sharp and funny after 9pm. Suggests late plans.',
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    category: 'lifestyle',
    icon: 'sunrise',
    description: 'Up at dawn and productive before anyone else is awake.',
    conflicts: ['night_owl', 'insomniac'],
    needDecay: { energy: 0.95 },
    skillMult: { fitness: 1.1 },
    llmHint: 'Chipper in the morning, fading by 9pm. Talks about sunrise runs, morning routines, and how much they got done before 8. Suggests early plans; leaves parties early.',
  },
  {
    id: 'adventurous',
    name: 'Adventurous',
    category: 'personality',
    icon: 'compass',
    description: 'New places, new food, new people. Routine is a cage.',
    conflicts: ['homebody', 'coward'],
    needDecay: { fun: 1.2 },
    skillMult: { athletics: 1.1, photography: 1.1, spanish: 1.15 },
    llmHint: 'Talks about trips, plans, wild ideas for the weekend. Says yes first, thinks later. Restless with routine. Tells travel stories. Encourages others to try the strange menu item.',
  },
  {
    id: 'homebody',
    name: 'Homebody',
    category: 'lifestyle',
    icon: 'home',
    description: 'Home is the best place. Going out takes convincing.',
    conflicts: ['adventurous', 'party_animal'],
    needDecay: { comfort: 1.1, social: 0.85 },
    skillMult: { cooking: 1.1, gardening: 1.1, crafting: 1.1 },
    stressMult: 0.95,
    llmHint: 'Talks about their place, their couch, their routines, what they are cooking. Suggests hosting instead of going out. Cozy, a bit reluctant, relieved when plans cancel.',
  },
  {
    id: 'geek',
    name: 'Geek',
    category: 'lifestyle',
    icon: 'cpu',
    description: 'Deep into games, tech, comics, or all three. Knows the lore.',
    conflicts: [],
    skillMult: { gaming: 1.4, programming: 1.3, logic: 1.2 },
    needDecay: { fun: 1.05 },
    llmHint: 'Enthusiastic, detailed, references games, shows, hardware, fandoms. Explains mechanics. A bit awkward socially at first, animated on their topics. Uses internet slang.',
  },
  {
    id: 'music_lover',
    name: 'Music Lover',
    category: 'lifestyle',
    icon: 'headphones',
    description: 'Always has something playing. Concerts are church.',
    conflicts: [],
    needDecay: { fun: 1.1 },
    skillMult: { music: 1.4, guitar: 1.3, piano: 1.3, singing: 1.3, dancing: 1.15 },
    llmHint: 'Asks what you listen to, talks about shows, albums, vinyl, playlists. Hums. Judges venues by their sound system. Knows the local scene.',
  },
  {
    id: 'animal_lover',
    name: 'Animal Lover',
    category: 'lifestyle',
    icon: 'paw',
    description: 'Every dog is a friend. Might own too many cats.',
    conflicts: [],
    needDecay: { social: 0.9 },
    llmHint: 'Talks to and about animals constantly, shows pet photos, stops for every dog on the street. Soft-hearted, volunteers at shelters. Judges people by how animals react to them.',
  },
  {
    id: 'vegetarian',
    name: 'Vegetarian',
    category: 'lifestyle',
    icon: 'leaf',
    description: 'Doesn\'t eat meat. Gets a bad moodlet if they do.',
    conflicts: [],
    skillMult: { cooking: 1.1, gardening: 1.1 },
    llmHint: 'Checks menus for veg options, asks about ingredients, knows the good vegetarian spots. Not preachy unless pushed; then has statistics. Grateful when hosts accommodate.',
  },
  {
    id: 'workaholic',
    name: 'Workaholic',
    category: 'lifestyle',
    icon: 'briefcase',
    description: 'Work is identity. Answers email at dinner; vacations feel wrong.',
    conflicts: ['lazy'],
    needDecay: { fun: 0.8, social: 0.9 },
    skillMult: { programming: 1.1, finance: 1.1, law: 1.1, negotiation: 1.1 },
    stressMult: 0.95,
    llmHint: 'Talks about work, deadlines, the boss, the project. Checks phone mid-conversation. Proud of long hours, dismissive of "balance". Relaxes only by talking about work differently.',
  },
  {
    id: 'perfectionist',
    name: 'Perfectionist',
    category: 'personality',
    icon: 'target',
    description: 'Good enough isn\'t. Takes longer, does it better, stresses more.',
    conflicts: ['lazy', 'slob'],
    stressMult: 1.2,
    skillMult: { cooking: 1.1, painting: 1.1, writing: 1.1, handiness: 1.1, programming: 1.1, baking: 1.15 },
    llmHint: 'Detail-oriented, self-critical, notices flaws in their own work first. Apologizes for things that were fine. Redoes tasks. Precise language, hates typos, high standards for others too.',
  },
  {
    id: 'clumsy',
    name: 'Clumsy',
    category: 'physical',
    icon: 'bandage',
    description: 'Trips, drops, spills, and bumps. Injuries happen more.',
    conflicts: [],
    skillMult: { dancing: 0.85, handiness: 0.9, athletics: 0.9 },
    llmHint: 'Self-deprecating about spills and bruises, tells stories about the time they fell. Knocks things over mid-conversation. Apologetic, good-humored about it.',
  },
  {
    id: 'brave',
    name: 'Brave',
    category: 'personality',
    icon: 'sword',
    description: 'Runs toward trouble. Stands up to bullies and bad landlords.',
    conflicts: ['coward'],
    stressMult: 0.85,
    llmHint: 'Direct, steady under pressure, speaks up when others go quiet. Will confront a rude stranger or step in during trouble. Calm voice in emergencies. Slightly reckless.',
  },
  {
    id: 'coward',
    name: 'Coward',
    category: 'personality',
    icon: 'ghost',
    description: 'Avoids confrontation, dark alleys, and the doctor. Fear rules many choices.',
    conflicts: ['brave', 'adventurous', 'thrill_seeker'],
    stressMult: 1.25,
    llmHint: 'Nervous, hedging, avoids conflict and risk. Makes excuses to leave scary situations. Worries out loud. Defers to others. Relieved when someone else takes charge.',
  },
  {
    id: 'snob',
    name: 'Snob',
    category: 'social',
    icon: 'wine',
    description: 'Has taste, and wants you to know it. Chain restaurants are beneath them.',
    conflicts: ['childish'],
    socialMult: 0.9,
    needDecay: { comfort: 1.15 },
    llmHint: 'Name-drops restaurants, wines, neighborhoods, schools. Subtly (or not) rates your choices. Uses "actually" a lot. Polished vocabulary, disdain for the cheap and popular.',
  },
  {
    id: 'childish',
    name: 'Childish',
    category: 'personality',
    icon: 'balloon',
    description: 'Playful and silly. Toys, cartoons, and pranks never got old.',
    conflicts: ['snob', 'stoic'],
    needDecay: { fun: 1.3 },
    skillMult: { parenting: 1.1, gaming: 1.1, comedy: 1.15 },
    llmHint: 'Goofy, enthusiastic, easily delighted, easily bored. Pranks, puns, cartoon references. Avoids "adult" conversations about taxes and bills. Sulks a little when told no.',
  },
  {
    id: 'hopeless_romantic',
    name: 'Hopeless Romantic',
    category: 'social',
    icon: 'heart-handshake',
    description: 'Falls hard and fast. Every date might be The One.',
    conflicts: ['commitment_issues'],
    stressMult: 1.05,
    llmHint: 'Sighs about love, reads into every text, talks about soulmates and fate. Intense and sweet early in relationships, crushed by rejection. Watches rom-coms unironically.',
  },
  {
    id: 'commitment_issues',
    name: 'Commitment Issues',
    category: 'social',
    icon: 'door-open',
    description: 'Gets nervous when things get serious — jobs, leases, relationships.',
    conflicts: ['family_oriented', 'loyal', 'hopeless_romantic'],
    socialMult: 0.95,
    llmHint: 'Keeps things light, dodges "what are we" talks, avoids long leases and long plans. Charming but slippery. Changes the subject when the future comes up. Values freedom.',
  },
  {
    id: 'party_animal',
    name: 'Party Animal',
    category: 'lifestyle',
    icon: 'party-popper',
    description: 'Lives for the night out. Knows every bartender by name.',
    conflicts: ['loner', 'homebody'],
    needDecay: { fun: 1.3, social: 1.3 },
    skillMult: { mixology: 1.2, dancing: 1.2, charisma: 1.1 },
    llmHint: 'Loud, fun, always planning the next night out. Talks about bars, shows, who was there. Encourages another round. Hungover mornings, unbothered. Everyone is "my guy".',
  },
  {
    id: 'spiritual',
    name: 'Spiritual',
    category: 'personality',
    icon: 'sun',
    description: 'Finds meaning in faith, meditation, or the universe. Calm under strain.',
    conflicts: ['skeptic', 'materialistic'],
    stressMult: 0.9,
    llmHint: 'Talks about gratitude, purpose, church or meditation or "the universe". Reflective, calm, non-judgmental on the surface. Offers to pray for you or recommends breathing. Comfortable with big questions.',
  },
  {
    id: 'skeptic',
    name: 'Skeptic',
    category: 'mental',
    icon: 'search',
    description: 'Wants evidence. Doubts horoscopes, salesmen, and easy answers.',
    conflicts: ['spiritual'],
    skillMult: { research: 1.2, logic: 1.15, law: 1.1 },
    llmHint: 'Questions claims, asks "says who?", cites sources. Dry, rational, a bit contrarian. Unimpressed by hype and superstition. Respects data, distrusts vibes.',
  },
  {
    id: 'generous',
    name: 'Generous',
    category: 'social',
    icon: 'gift',
    description: 'Picks up the check, lends money, gives time. Sometimes to a fault.',
    conflicts: ['mean'],
    socialMult: 1.1,
    llmHint: 'Offers to pay, to help, to host. Gives gifts and compliments. Uncomfortable receiving. Talks about others\' needs more than their own. Can be taken advantage of.',
  },
  {
    id: 'gossip',
    name: 'Gossip',
    category: 'social',
    icon: 'message-circle',
    description: 'Knows everything about everyone, and shares it.',
    conflicts: [],
    socialMult: 1.05,
    needDecay: { social: 1.15 },
    llmHint: 'Leans in with "did you hear about…". Trades information, asks nosy questions, cannot keep a secret. Fun to talk to, risky to confide in. Knows the neighborhood drama.',
  },
  {
    id: 'vain',
    name: 'Vain',
    category: 'personality',
    icon: 'mirror',
    description: 'Looks matter — theirs most of all. Mirrors are irresistible.',
    conflicts: ['slob'],
    needDecay: { hygiene: 1.2 },
    socialMult: 0.95,
    skillMult: { photography: 1.1, charisma: 1.05 },
    llmHint: 'Talks about appearance, outfits, skincare, the gym. Fishes for compliments, checks reflection, posts selfies. Judges others by looks. Charming when flattered.',
  },
  {
    id: 'self_assured',
    name: 'Self-Assured',
    category: 'personality',
    icon: 'crown',
    description: 'Comfortable in their skin. Criticism rolls off; setbacks feel temporary.',
    conflicts: ['anxious', 'jealous'],
    stressMult: 0.85,
    skillMult: { charisma: 1.15, negotiation: 1.1 },
    llmHint: 'Calm, confident, unhurried. States opinions without hedging, takes compliments gracefully, laughs off insults. Does not need validation. Can read as arrogant.',
  },
  {
    id: 'anxious',
    name: 'Anxious',
    category: 'mental',
    icon: 'alert-circle',
    description: 'Worry is the default setting. Stress climbs fast and lingers.',
    conflicts: ['self_assured', 'stoic'],
    stressMult: 1.4,
    needDecay: { energy: 1.05 },
    llmHint: 'Worries aloud about what could go wrong, apologizes a lot, over-explains, double-checks plans. Rambles when nervous. Grateful for reassurance. Avoids phone calls.',
  },
  {
    id: 'empathetic',
    name: 'Empathetic',
    category: 'social',
    icon: 'heart-pulse',
    description: 'Feels what others feel. Great listener; absorbs other people\'s bad days.',
    conflicts: ['mean'],
    socialMult: 1.2,
    stressMult: 1.1,
    skillMult: { parenting: 1.15, medicine: 1.1, charisma: 1.05 },
    llmHint: 'Notices moods and names them gently ("you seem tired"). Listens more than talks, validates feelings, remembers what you told them. Drained by conflict and other people\'s pain.',
  },
  {
    id: 'stoic',
    name: 'Stoic',
    category: 'personality',
    icon: 'mountain',
    description: 'Feels things; shows little. Unbothered by discomfort and drama.',
    conflicts: ['hot_headed', 'anxious', 'childish'],
    stressMult: 0.7,
    socialMult: 0.95,
    needDecay: { comfort: 0.85 },
    llmHint: 'Few words, flat delivery, unflappable. Does not complain about pain, weather, or setbacks. Practical advice, no fuss. Warmth shows in actions, not words.',
  },
  {
    id: 'hypochondriac',
    name: 'Hypochondriac',
    category: 'mental',
    icon: 'thermometer',
    description: 'Every sniffle is something serious. Knows the urgent care hours by heart.',
    conflicts: [],
    stressMult: 1.2,
    skillMult: { medicine: 1.1, research: 1.05 },
    llmHint: 'Mentions symptoms, searches them, asks if you think it is serious. Carries hand sanitizer and vitamins. Avoids sick people. Talks about doctors and test results.',
  },
  {
    id: 'thrill_seeker',
    name: 'Thrill Seeker',
    category: 'personality',
    icon: 'zap',
    description: 'Needs the rush — speed, heights, bets, risk.',
    conflicts: ['coward'],
    needDecay: { fun: 1.3 },
    stressMult: 0.9,
    skillMult: { driving: 1.15, athletics: 1.1 },
    llmHint: 'Talks about the fastest, highest, riskiest thing they did last. Bored by safe plans, proposes wild ones. Gambles, speeds, dares. Laughs at danger; impatient with caution.',
  },
];

export const TRAITS: Record<string, TraitDef> = (() => {
  const out: Record<string, TraitDef> = {};
  for (const d of defs) out[d.id] = { ...d, conflicts: [...(d.conflicts ?? [])] };
  // conflicts are symmetric: if A conflicts with B, B conflicts with A
  for (const t of Object.values(out)) for (const c of t.conflicts) if (out[c] && !out[c].conflicts.includes(t.id)) out[c].conflicts.push(t.id);
  return out;
})();

export const TRAIT_IDS = Object.keys(TRAITS);

export function hasTrait(sim: { personality: { traits: string[] } }, id: string): boolean {
  return sim.personality.traits.includes(id);
}
